Repository oracle/accelerated-data-science, pull requests merged in 2023-06, with the labels that each got.

#208 Added tag for SPARK_VERSION 3.2.1
  ads/dataflow/dataflow.py
  ads/jobs/builders/infrastructure/dataflow.py
Labels: OCA Verified

#213 ODSC-43403/Removed ads.dataflow.dataflow Module
  .coveragerc
  ads/dataflow/__init__.py
  ads/dataflow/dataflow.py
  ads/dataflow/dataflowsummary.py
  ads/jobs/builders/infrastructure/dataflow.py
  docs/source/user_guide/data_flow/legacy_dataflow.rst
Labels: OCA Verified

#214 Added checker for shape details for job
  ads/jobs/builders/infrastructure/dsc_job.py
  tests/unitary/default_setup/jobs/test_jobs_base.py
Labels: OCA Verified

#204 Added support for mounting object storage service for job.
  ads/common/dsc_file_system.py
  ads/jobs/builders/infrastructure/dsc_job.py
  tests/unitary/default_setup/jobs/test_jobs_mount_file_system.py
Labels: enhancement, OCA Verified

#217 ODSC-42687. Add ads entry point to invoke ads.cli:cli
  ads/ads
  setup.py
Labels: OCA Verified

#211 Added validation for driver and executor shape details.
  ads/jobs/builders/infrastructure/dataflow.py
  tests/unitary/default_setup/jobs/test_jobs_dataflow.py
Labels: enhancement, OCA Verified

#218 bugfix/ODSC-43563/entryscript_mounted_as_directory
  ads/opctl/backend/local.py
  ads/opctl/cli.py
  docs/source/user_guide/cli/opctl/localdev/local_deployment.rst
Labels: bug, OCA Verified

#216 Support uploading large artifact for model deployment.
  ads/model/deployment/model_deployment.py
  ads/model/deployment/model_deployment_runtime.py
  docs/source/user_guide/model_registration/model_deploy_byoc.rst
  tests/unitary/default_setup/model_deployment/test_model_deployment_v2.py
Labels: enhancement, OCA Verified

#212 feature/ODSC-41635/Support Data Flow Pools
  ads/jobs/builders/infrastructure/dataflow.py
  docs/source/user_guide/apachespark/dataflow-spark-magic.rst
  docs/source/user_guide/apachespark/dataflow.rst
  tests/unitary/default_setup/jobs/test_jobs_dataflow.py
Labels: enhancement, OCA Verified, waiting service GA

#221 Deprecated ModelDeploymentProperties and ModelDeployer classes
  ads/model/deployment/model_deployer.py
  ads/model/deployment/model_deployment.py
  ads/model/deployment/model_deployment_properties.py
  ads/model/generic_model.py
  ads/model/service/oci_datascience_model.py
  docs/source/user_guide/model_registration/model_deploy.rst
  tests/unitary/default_setup/model/test_oci_datascience_model.py
  tests/unitary/default_setup/model_deployment/test_model_deployment_v2.py
  tests/unitary/with_extras/model/test_generic_model.py
Labels: OCA Verified, class/api deprecation

#223 Update THIRD_PARTY_LICENSES.txt
  .github/workflows/add-3plicense-warning.yml
  THIRD_PARTY_LICENSES.txt
Labels: documentation, OCA Verified

#225 [ADS OPCTL] Display prebuilt watch command for monitoring jobs with OPCTL.
  ads/opctl/backend/ads_dataflow.py
  ads/opctl/backend/ads_ml_job.py
  ads/opctl/backend/ads_ml_pipeline.py
  ads/opctl/backend/base.py
  ads/opctl/cmds.py
  ads/opctl/decorator/__init__.py
  ads/opctl/decorator/common.py
  docs/source/user_guide/cli/opctl/_template/jobs.rst
Labels: OCA Verified

#230 ADS release v2.8.6
  ads/ads_version.json
  docs/source/release_notes.rst
Labels: OCA Verified

#229 datatype - infer schema changes and integration tests
  ads/common/oci_mixin.py
  ads/feature_store/common/enums.py
  ads/feature_store/common/utils/feature_schema_mapper.py
  ads/feature_store/common/utils/utility.py
  ads/feature_store/execution_strategy/engine/spark_engine.py
  ads/feature_store/execution_strategy/spark/spark_execution.py
  ads/feature_store/feature_group.py
  tests/integration/feature_store/test_datatype_pandas_array.py
  tests/integration/feature_store/test_datatype_pandas_basic.py
  tests/integration/feature_store/test_datatype_pandas_mixed.py
  tests/integration/feature_store/test_datatype_pandas_object.py
  tests/integration/feature_store/test_datatype_spark_array_map.py
  tests/integration/feature_store/test_datatype_spark_basic.py
  tests/unitary/install_required/feature_store/test_feature_group.py
  tests/unitary/install_required/feature_store/test_transformation.py
Labels: OCA Verified

#232 Update to version 2.8.6
  .github/workflows/add-3plicense-warning.yml
  THIRD_PARTY_LICENSES.txt
  ads/ads_version.json
  ads/jobs/builders/infrastructure/dataflow.py
  ads/model/deployment/model_deployer.py
  ads/model/deployment/model_deployment.py
  ads/model/deployment/model_deployment_properties.py
  ads/model/deployment/model_deployment_runtime.py
  ads/model/generic_model.py
  ads/model/service/oci_datascience_model.py
  ads/opctl/backend/ads_dataflow.py
  ads/opctl/backend/ads_ml_job.py
  ads/opctl/backend/ads_ml_pipeline.py
  ads/opctl/backend/base.py
  ads/opctl/backend/local.py
  ads/opctl/cli.py
  ads/opctl/cmds.py
  ads/opctl/decorator/__init__.py
  ads/opctl/decorator/common.py
  docs/source/release_notes.rst
  docs/source/user_guide/apachespark/dataflow-spark-magic.rst
  docs/source/user_guide/apachespark/dataflow.rst
  docs/source/user_guide/cli/authentication.rst
  docs/source/user_guide/cli/opctl/_template/jobs.rst
  docs/source/user_guide/cli/opctl/localdev/local_deployment.rst
  docs/source/user_guide/model_registration/model_deploy.rst
  docs/source/user_guide/model_registration/model_deploy_byoc.rst
  tests/integration/jobs/test_dsc_job.py
  tests/unitary/default_setup/jobs/test_jobs_dataflow.py
  tests/unitary/default_setup/model/test_oci_datascience_model.py
  tests/unitary/default_setup/model_deployment/test_model_deployment_v2.py
  tests/unitary/with_extras/model/test_generic_model.py
Labels: OCA Verified

#234 Add pre-commit hooks for ocids, copyright and secrets
  .gitleaks.toml
  .pre-commit-config.yaml
Labels: OCA Verified

#224 docs/odsc 41635/update doc for dataflow pool support
  docs/source/user_guide/apachespark/dataflow-spark-magic.rst
  docs/source/user_guide/apachespark/dataflow.rst
Labels: documentation, OCA Verified, do not merge

#233 stats generation done using mlm and transformation query support for SQL
  THIRD_PARTY_LICENSES.txt
  ads/common/decorator/runtime_dependency.py
  ads/feature_store/common/spark_session_singleton.py
  ads/feature_store/common/utils/feature_schema_mapper.py
  ads/feature_store/common/utils/transformation_query_validator.py
  ads/feature_store/execution_strategy/spark/spark_execution.py
  ads/feature_store/feature_statistics/pydeequ_service.py
  ads/feature_store/feature_statistics/statistics_service.py
  ads/feature_store/feature_store.py
  ads/feature_store/feature_store_registrar.py
  ads/feature_store/templates/feature_store_template.yaml
  ads/feature_store/transformation.py
  setup.py
  tests/data/feature_store_minimal.yaml
  tests/integration/feature_store/test_base.py
  tests/integration/feature_store/test_transformation.py
Labels: OCA Verified

#236 Odsc 41744/move incorrect opctl information
  ads/opctl/backend/ads_dataflow.py
  ads/opctl/backend/ads_ml_job.py
  ads/opctl/backend/ads_ml_pipeline.py
  ads/opctl/cli.py
  tests/unitary/with_extras/opctl/test_opctl_dataflow_backend.py
  tests/unitary/with_extras/opctl/test_opctl_ml_job_backend.py
  tests/unitary/with_extras/opctl/test_opctl_ml_pipeline_backend.py
Labels: OCA Verified

#231 Added support for security token authentication
  ads/common/auth.py
  ads/opctl/cli.py
  ads/opctl/config/merger.py
  docs/source/user_guide/cli/authentication.rst
  tests/unitary/default_setup/auth/test_auth.py
Labels: OCA Verified, new feature

#237 ADS release v2.8.7
  .github/workflows/publish-to-readthedocs.yml
  ads/ads_version.json
  docs/source/release_notes.rst
  setup.py
Labels: OCA Verified

#238 List FeatureGroupJobs Bug Fixing
  ads/feature_store/service/oci_feature_group_job.py
Labels: OCA Verified

#235 Query builder fix for Joins
  .github/workflows/publish-to-readthedocs.yml
  .gitleaks.toml
  .pre-commit-config.yaml
  ads/ads_version.json
  ads/common/auth.py
  ads/feature_store/common/spark_session_singleton.py
  ads/feature_store/common/utils/feature_schema_mapper.py
  ads/feature_store/common/utils/transformation_query_validator.py
  ads/feature_store/docs/Dockerfile
  ads/feature_store/docs/Makefile
  ads/feature_store/docs/conf.py
  ads/feature_store/docs/requirements.txt
  ads/feature_store/docs/source/conf.py
  ads/feature_store/docs/source/dataset.rst
  ads/feature_store/docs/source/dataset_job.rst
  ads/feature_store/docs/source/demo.rst
  ads/feature_store/docs/source/entity.rst
  ads/feature_store/docs/source/feature_group.rst
  ads/feature_store/docs/source/feature_group_job.rst
  ads/feature_store/docs/source/feature_store.rst
  ads/feature_store/docs/source/figures/dataset_lineage.png
  ads/feature_store/docs/source/figures/feature_group_lineage.png
  ads/feature_store/docs/source/figures/logo-dark-mode.png
  ads/feature_store/docs/source/figures/logo-light-mode.png
  ads/feature_store/docs/source/figures/overview.png
  ads/feature_store/docs/source/figures/stats_1.png
  ads/feature_store/docs/source/figures/stats_2.png
  ads/feature_store/docs/source/figures/validation.png
  ads/feature_store/docs/source/index.rst
  ads/feature_store/docs/source/notebook.rst
  ads/feature_store/docs/source/overview.rst
  ads/feature_store/docs/source/quickstart.rst
  ads/feature_store/docs/source/release_notes.rst
  ads/feature_store/docs/source/terraform.rst
  ads/feature_store/docs/source/transformation.rst
  ads/feature_store/execution_strategy/spark/spark_execution.py
  ads/feature_store/feature_group.py
  ads/feature_store/feature_statistics/statistics_service.py
  ads/feature_store/feature_store.py
  ads/feature_store/feature_store_registrar.py
  ads/feature_store/query/generator/query_generator.py
  ads/feature_store/query/query.py
  ads/feature_store/response/response_builder.py
  ads/feature_store/statistics.py
  ads/feature_store/transformation.py
  ads/opctl/backend/ads_dataflow.py
  ads/opctl/backend/ads_ml_job.py
  ads/opctl/backend/ads_ml_pipeline.py
  ads/opctl/cli.py
  ads/opctl/config/merger.py
  docs/source/release_notes.rst
  docs/source/user_guide/apachespark/dataflow-spark-magic.rst
  docs/source/user_guide/apachespark/dataflow.rst
  docs/source/user_guide/cli/authentication.rst
  setup.py
  tests/unitary/default_setup/auth/test_auth.py
  tests/unitary/install_required/feature_store/test_query.py
  tests/unitary/with_extras/opctl/test_opctl_dataflow_backend.py
  tests/unitary/with_extras/opctl/test_opctl_ml_job_backend.py
  tests/unitary/with_extras/opctl/test_opctl_ml_pipeline_backend.py
Labels: OCA Verified
