Repository oracle/accelerated-data-science, pull requests merged in 2023-07, with the labels that each got.

#246 DataType Changes, validation output transpose
  ads/feature_store/common/enums.py
  ads/feature_store/common/spark_session_singleton.py
  ads/feature_store/common/utils/feature_schema_mapper.py
  ads/feature_store/common/utils/utility.py
  ads/feature_store/docs/source/feature_group.rst
  ads/feature_store/docs/source/release_notes.rst
  ads/feature_store/docs/source/terraform.rst
  ads/feature_store/execution_strategy/spark/spark_execution.py
  ads/feature_store/feature_group_job.py
  ads/feature_store/validation_output.py
  tests/integration/feature_store/test_base.py
  tests/integration/feature_store/test_dataset_validations.py
  tests/integration/feature_store/test_datatype_pandas_array.py
  tests/integration/feature_store/test_datatype_pandas_mixed.py
  tests/integration/feature_store/test_datatype_pandas_object.py
  tests/integration/feature_store/test_datatype_spark_array_map.py
  tests/integration/feature_store/test_datatype_spark_basic.py
  tests/integration/feature_store/test_feature_group_validations.py
  tests/integration/feature_store/test_input_feature_details.py
Labels: OCA Verified

#248 removed spark magic from docs
  ads/feature_store/docs/source/demo.rst
Labels: OCA Verified

#249 added terraform version in the command
  ads/feature_store/common/spark_session_singleton.py
  ads/feature_store/common/utils/feature_schema_mapper.py
  ads/feature_store/common/utils/transformation_query_validator.py
  ads/feature_store/common/utils/utility.py
  ads/feature_store/docs/source/figures/resource_manager.png
  ads/feature_store/docs/source/figures/resource_manager_feature_store_stack.png
  ads/feature_store/docs/source/figures/resource_manager_home.png
  ads/feature_store/docs/source/quickstart.rst
  ads/feature_store/docs/source/release_notes.rst
  ads/feature_store/docs/source/terraform.rst
  ads/feature_store/entity.py
  ads/feature_store/execution_strategy/spark/spark_execution.py
  ads/feature_store/feature_group.py
  ads/feature_store/feature_store.py
  ads/feature_store/feature_store_registrar.py
  ads/feature_store/transformation.py
  tests/integration/feature_store/test_base.py
  tests/integration/feature_store/test_transformation.py
Labels: OCA Verified

#247 code changes to tie ingestion and validation
  ads/feature_store/common/utils/utility.py
  ads/feature_store/data_validation/great_expectation.py
  ads/feature_store/execution_strategy/spark/spark_execution.py
Labels: OCA Verified

#251 ODSC-44021: Fix developer mode logic. Reduce testing time
  ads/feature_store/common/spark_session_singleton.py
  ads/feature_store/common/utils/utility.py
Labels: OCA Verified

#252 Temporary fix to resolve circular import issue
  ads/feature_store/common/spark_session_singleton.py
  ads/feature_store/common/utils/utility.py
  ads/feature_store/docs/source/release_notes.rst
  ads/feature_store/docs/source/terraform.rst
  ads/feature_store/execution_strategy/spark/spark_execution.py
  tests/integration/feature_store/test_datatype_pandas_mixed.py
Labels: OCA Verified

#241 Refresh jobs images, fix key issue for cuda install, updated optcl tests
  .gitleaks.toml
  .pre-commit-config.yaml
  ads/opctl/docker/Dockerfile.job
  ads/opctl/docker/Dockerfile.job.gpu
  ads/opctl/docker/base-env.yaml
  tests/unitary/with_extras/opctl/test_opctl_local_backend.py
  tests/unitary/with_extras/opctl/test_opctl_local_model_deployment_backend.py
Labels: OCA Verified

#253 Update documentation for feature store
  ads/feature_store/docs/source/dataset.rst
  ads/feature_store/docs/source/feature_group.rst
  ads/feature_store/docs/source/feature_validation.rst
  ads/feature_store/docs/source/figures/stats_1.png
  ads/feature_store/docs/source/index.rst
  ads/feature_store/docs/source/overview.rst
  ads/feature_store/docs/source/statistics.rst
  ads/feature_store/docs/source/terraform.rst
Labels: OCA Verified

#259 Odsc 44980: fix unittests
  .gitleaks.toml
  .pre-commit-config.yaml
  ads/common/oci_client.py
  ads/common/oci_mixin.py
  ads/common/serializer.py
  ads/jobs/__init__.py
  ads/jobs/ads_job.py
  ads/jobs/builders/infrastructure/dsc_job.py
  ads/jobs/builders/infrastructure/dsc_job_runtime.py
  ads/jobs/builders/runtimes/artifact.py
  ads/jobs/builders/runtimes/python_runtime.py
  ads/jobs/builders/runtimes/pytorch_runtime.py
  ads/jobs/serializer.py
  ads/jobs/templates/driver_oci.py
  ads/jobs/templates/driver_pytorch.py
  ads/jobs/templates/driver_utils.py
  ads/jobs/templates/hostname_from_env.c
  ads/jobs/templates/oci_metrics.py
  ads/model/framework/pytorch_model.py
  ads/opctl/docker/Dockerfile.job
  ads/opctl/docker/Dockerfile.job.gpu
  ads/opctl/docker/base-env.yaml
  setup.py
  tests/unitary/default_setup/jobs/test_gpu_metrics.py
  tests/unitary/default_setup/jobs/test_jobs_pytorch_ddp.py
  tests/unitary/with_extras/jobs/__init__.py
  tests/unitary/with_extras/jobs/test_pytorch_ddp.py
  tests/unitary/with_extras/opctl/test_opctl_local_backend.py
  tests/unitary/with_extras/opctl/test_opctl_local_model_deployment_backend.py
Labels: OCA Verified

#261 Fix test faliures
  tests/integration/feature_store/test_base.py
Labels: OCA Verified

#255 validation output changes
  ads/feature_store/dataset.py
  ads/feature_store/docs/source/dataset.rst
  ads/feature_store/docs/source/feature_group.rst
  ads/feature_store/docs/source/feature_validation.rst
  ads/feature_store/docs/source/figures/dataset_statistics.png
  ads/feature_store/docs/source/figures/dataset_validation_results.png
  ads/feature_store/docs/source/figures/dataset_validation_summary.png
  ads/feature_store/docs/source/figures/validation_results.png
  ads/feature_store/docs/source/figures/validation_summary.png
  ads/feature_store/feature_group.py
  ads/feature_store/validation_output.py
  tests/integration/feature_store/test_dataset_validations.py
  tests/integration/feature_store/test_feature_group_validations.py
Labels: OCA Verified

#258 ODSC-44980: Prepare workflows for feature store merge
  .github/workflows/run-unittests-default_setup.yml
  .github/workflows/run-unittests.yml
Labels: OCA Verified

#262 Moving tests to the new designated folder
  ads/feature_store/docs/source/conf.py
  ads/feature_store/docs/source/feature_validation.rst
  ads/feature_store/docs/source/release_notes.rst
  ads/feature_store/docs/source/terraform.rst
  tests/unitary/with_extras/feature_store/__init__.py
  tests/unitary/with_extras/feature_store/test_dataset.py
  tests/unitary/with_extras/feature_store/test_dataset_job.py
  tests/unitary/with_extras/feature_store/test_entity.py
  tests/unitary/with_extras/feature_store/test_feature_group.py
  tests/unitary/with_extras/feature_store/test_feature_group_job.py
  tests/unitary/with_extras/feature_store/test_feature_store.py
  tests/unitary/with_extras/feature_store/test_feature_store_registrar.py
  tests/unitary/with_extras/feature_store/test_oci_dataset.py
  tests/unitary/with_extras/feature_store/test_oci_dataset_job.py
  tests/unitary/with_extras/feature_store/test_oci_entity.py
  tests/unitary/with_extras/feature_store/test_oci_feature_group.py
  tests/unitary/with_extras/feature_store/test_oci_feature_group_job.py
  tests/unitary/with_extras/feature_store/test_oci_feature_store.py
  tests/unitary/with_extras/feature_store/test_oci_transformation.py
  tests/unitary/with_extras/feature_store/test_query.py
  tests/unitary/with_extras/feature_store/test_transformation.py
Labels: OCA Verified

#264 ODSC-44446. Multiple fixes to documentation
  docs/source/ads.explanations.rst
  docs/source/ads.jobs.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/user_guide/big_data_service/file_management.rst
  docs/source/user_guide/big_data_service/sql_data_management.rst
  docs/source/user_guide/data_transformation/data_transformation.rst
  docs/source/user_guide/model_training/ads_tuner.rst
  docs/source/user_guide/model_training/figures/ads_tuner_10_0.png
  docs/source/user_guide/model_training/figures/ads_tuner_11_0.png
  docs/source/user_guide/model_training/figures/ads_tuner_12_0.png
  docs/source/user_guide/model_training/figures/ads_tuner_13_0.png
  docs/source/user_guide/model_training/figures/ads_tuner_14_0.png
  docs/source/user_guide/model_training/figures/ads_tuner_15_1.png
Labels: documentation, OCA Verified

#266 Loosen pyyaml version, which broken for latest cython.
  ads/pipeline/ads_pipeline.py
  ads/secrets/secrets.py
  setup.py
  tests/unitary/default_setup/secret/test_secretkeeper_adw.py
  tests/unitary/default_setup/secret/test_secretkeeper_auth_token.py
  tests/unitary/default_setup/secret/test_secretkeeper_bds.py
  tests/unitary/default_setup/secret/test_secretkeeper_mysqldb.py
  tests/unitary/default_setup/secret/test_secretkeeper_oracledb.py
Labels: OCA Verified

#256 Added flex shape for opctl config
  ads/model/deployment/model_deployment.py
  ads/model/deployment/model_deployment_infrastructure.py
  ads/opctl/cmds.py
  ads/opctl/config/merger.py
  tests/unitary/with_extras/opctl/test_files/modeldeployment_conda.yaml
  tests/unitary/with_extras/opctl/test_files/modeldeployment_container.yaml
  tests/unitary/with_extras/opctl/test_opctl_cmds.py
  tests/unitary/with_extras/opctl/test_opctl_config.py
  tests/unitary/with_extras/opctl/test_opctl_model_deployment_backend.py
Labels: OCA Verified

#269 Fixed opctl commands.
  ads/opctl/cli.py
Labels: OCA Verified

#270 added notebook for schema evolution
  ads/feature_store/docs/source/notebook.rst
Labels: OCA Verified

#271 Fix bugs for PyTorchDistributedRuntime
  ads/jobs/builders/runtimes/pytorch_runtime.py
  ads/jobs/templates/driver_pytorch.py
  tests/unitary/default_setup/jobs/test_jobs_pytorch_ddp.py
Labels: OCA Verified

#242 Fixed job run opctl.
  ads/opctl/cli.py
  ads/opctl/cmds.py
Labels: OCA Verified

#254 Deprecated DatasetFactory class and refactored code.
  ads/dataset/dataset.py
  ads/dataset/dataset_browser.py
  ads/dataset/factory.py
  ads/dataset/helper.py
Labels: OCA Verified, class/api deprecation

#273 fixes in forecast operator
  ads/opctl/operator/cmd.py
  ads/opctl/operator/lowcode/forecast/__init__.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/utils.py
Labels: OCA Verified

#260 Interoperability with model catalog
  ads/feature_store/dataset.py
  ads/feature_store/docs/source/dataset.rst
  ads/feature_store/docs/source/quickstart.rst
  ads/feature_store/mixin/oci_feature_store.py
  ads/feature_store/validation_output.py
  ads/model/generic_model.py
  tests/integration/feature_store/test_base.py
  tests/integration/feature_store/test_dataset_validations.py
Labels: OCA Verified
