Repository oracle/accelerated-data-science, pull requests merged in 2023-10, with the labels that each got.

#363 Moves operator information form the init file to the MLoperator yaml.
  MANIFEST.in
  ads/opctl/backend/ads_dataflow.py
  ads/opctl/backend/ads_ml_job.py
  ads/opctl/backend/local.py
  ads/opctl/operator/cli.py
  ads/opctl/operator/cmd.py
  ads/opctl/operator/common/operator_loader.py
  ads/opctl/operator/common/operator_schema.yaml
  ads/opctl/operator/lowcode/forecast/MLoperator
  ads/opctl/operator/lowcode/forecast/README.md
  ads/opctl/operator/lowcode/forecast/__init__.py
  docs/source/user_guide/operators/common/explore.rst
  docs/source/user_guide/operators/common/figures/build_operator_conda.png
  docs/source/user_guide/operators/common/figures/build_operator_image.png
  docs/source/user_guide/operators/common/figures/operator_config_verify.png
  docs/source/user_guide/operators/common/figures/operator_config_verify_result.png
  docs/source/user_guide/operators/common/figures/operator_info.png
  docs/source/user_guide/operators/common/figures/operator_info1.png
  docs/source/user_guide/operators/common/figures/operator_init.png
  docs/source/user_guide/operators/common/figures/operator_list.png
  docs/source/user_guide/operators/common/figures/publish_operator_conda.png
  docs/source/user_guide/operators/common/figures/publish_operator_image.png
  docs/source/user_guide/operators/common/run.rst
Labels: OCA Verified

#346 Added support to cancel all job runs
  ads/jobs/ads_job.py
  ads/jobs/builders/infrastructure/dsc_job.py
  ads/opctl/backend/ads_ml_job.py
  ads/opctl/cmds.py
  tests/unitary/default_setup/jobs/test_jobs_base.py
  tests/unitary/with_extras/opctl/test_opctl_cmds.py
Labels: OCA Verified, draft, new feature

#360 Extended operator errors and added forecast specific exceptions
  ads/opctl/operator/common/errors.py
  ads/opctl/operator/common/operator_config.py
  ads/opctl/operator/lowcode/forecast/errors.py
  ads/opctl/operator/lowcode/forecast/schema.yaml
  ads/opctl/operator/lowcode/forecast/utils.py
  ads/opctl/operator/runtime/runtime.py
Labels: OCA Verified

#369 Migrate feature store to separate SDK
  ads/common/oci_mixin.py
  ads/feature_store/dataset.py
  ads/feature_store/dataset_job.py
  ads/feature_store/entity.py
  ads/feature_store/feature_group.py
  ads/feature_store/feature_group_job.py
  ads/feature_store/feature_store.py
  ads/feature_store/mixin/oci_feature_store.py
  ads/feature_store/service/oci_dataset.py
  ads/feature_store/service/oci_dataset_job.py
  ads/feature_store/service/oci_entity.py
  ads/feature_store/service/oci_feature_group.py
  ads/feature_store/service/oci_feature_group_job.py
  ads/feature_store/service/oci_feature_store.py
  ads/feature_store/service/oci_lineage.py
  ads/feature_store/service/oci_transformation.py
  ads/feature_store/transformation.py
Labels: OCA Verified

#367 [ODSC-47260] Global Explainer Class : Feature/forecast explain
  ads/opctl/operator/lowcode/forecast/environment.yaml
  ads/opctl/operator/lowcode/forecast/model/arima.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
  ads/opctl/operator/lowcode/forecast/model/prophet.py
Labels: OCA Verified

#374 Re-arrange unitary tests workflows
  .github/workflows/create-more-space/action.yml
  .github/workflows/run-unittests-default_setup.yml
  .github/workflows/run-unittests-py38-cov-report.yml
  .github/workflows/run-unittests-py39-py310.yml
  .github/workflows/set-dummy-conf/action.yml
  .pre-commit-config.yaml
Labels: OCA Verified

#368 Added support for customizing path for job mount file system
  ads/common/dsc_file_system.py
  ads/jobs/builders/infrastructure/dsc_job.py
  tests/unitary/default_setup/jobs/test_jobs_mount_file_system.py
Labels: OCA Verified, new feature

#240 Added warning for load balancer
  ads/model/deployment/model_deployment.py
  ads/model/deployment/model_deployment_runtime.py
  tests/unitary/default_setup/model_deployment/test_model_deployment.py
Labels: enhancement, OCA Verified

#372 Update distributed training CLI to add "ray" framework.
  ads/opctl/distributed/cli.py
Labels: OCA Verified

#371 Update `ads.set_auth()` to use both customized config and signer
  ads/common/auth.py
Labels: OCA Verified

#354 Streaming dataframe support
  ads/feature_store/common/enums.py
  ads/feature_store/common/utils/transformation_utils.py
  ads/feature_store/dataset.py
  ads/feature_store/dataset_job.py
  ads/feature_store/docs/source/dataset.rst
  ads/feature_store/docs/source/dataset_job.rst
  ads/feature_store/docs/source/entity.rst
  ads/feature_store/docs/source/feature_group.rst
  ads/feature_store/docs/source/feature_group_job.rst
  ads/feature_store/docs/source/feature_store.rst
  ads/feature_store/docs/source/transformation.rst
  ads/feature_store/execution_strategy/delta_lake/delta_lake_service.py
  ads/feature_store/execution_strategy/engine/spark_engine.py
  ads/feature_store/execution_strategy/execution_strategy.py
  ads/feature_store/execution_strategy/spark/spark_execution.py
  ads/feature_store/feature_group.py
  ads/feature_store/feature_group_job.py
  tests/integration/feature_store/test_data/credit_score_batch_1.csv
  tests/integration/feature_store/test_data/credit_score_batch_2.csv
  tests/integration/feature_store/test_streaming_dataframe_feature_group.py
Labels: OCA Verified

#375 ODSC-47259 Local Explainer Class : Feature/forecast explain
  ads/opctl/operator/lowcode/forecast/model/automlx.py
Labels: OCA Verified

#376 ODSC-48247/Update Doc On ModelDeployment Default Shape Name Selection
  ads/model/artifact_uploader.py
  ads/model/datascience_model.py
  docs/source/user_guide/model_registration/_template/deploy.rst
  docs/source/user_guide/model_registration/_template/prepare_save_deploy.rst
  docs/source/user_guide/model_serialization/_template/prepare_save_deploy.rst
  docs/source/user_guide/model_serialization/boilerplate/deploy.rst
  docs/source/user_guide/model_serialization/boilerplate/initialize.rst
Labels: OCA Verified

#358 [DOCS] Large Language Model section.
  docs/source/user_guide/model_registration/introduction.rst
  docs/source/user_guide/model_registration/large_language_model.rst
  docs/source/user_guide/model_registration/model_load.rst
  docs/source/user_guide/model_registration/tabs/ads-md-deploy-offline.rst
  docs/source/user_guide/model_registration/tabs/ads-md-deploy-online.rst
  docs/source/user_guide/model_registration/tabs/env-var-offline.rst
  docs/source/user_guide/model_registration/tabs/env-var-online.rst
  docs/source/user_guide/model_registration/tabs/run_md.rst
  docs/source/user_guide/model_registration/tabs/run_predict.rst
Labels: documentation, OCA Verified

#373 Added docs for mounting file systems for job.
  docs/source/user_guide/jobs/infra_and_runtime.rst
  docs/source/user_guide/jobs/tabs/infra_config.rst
  docs/source/user_guide/jobs/tabs/quick_start_job.rst
Labels: OCA Verified

#380 ADS release 2.8.11
  docs/source/release_notes.rst
  pyproject.toml
Labels: OCA Verified

#377 fixed bug in holdout data summary metrics per horizon
  ads/opctl/operator/lowcode/forecast/const.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/utils.py
Labels: OCA Verified

#384 Run operator within "ads opctl run"
  ads/opctl/backend/ads_ml_job.py
  ads/opctl/backend/local.py
  ads/opctl/cli.py
  ads/opctl/cmds.py
  ads/opctl/operator/__init__.py
  ads/opctl/operator/cli.py
  ads/opctl/operator/cmd.py
  ads/opctl/operator/common/backend_factory.py
  ads/opctl/operator/common/operator_config.py
  ads/opctl/operator/common/operator_loader.py
  ads/opctl/operator/common/operator_yaml_generator.py
  ads/opctl/operator/lowcode/forecast/MLoperator
  ads/opctl/operator/lowcode/forecast/__init__.py
  ads/opctl/operator/lowcode/forecast/cmd.py
  ads/opctl/operator/lowcode/forecast/schema.yaml
  docs/source/user_guide/cli/opctl/configure.rst
  docs/source/user_guide/operators/common/figures/operator_init.png
  docs/source/user_guide/operators/common/run.rst
  tests/unitary/with_extras/operator/test_cmd.py
  tests/unitary/with_extras/operator/test_common_backend_factory.py
  tests/unitary/with_extras/operator/test_files/dataflow_dataflow.yaml
  tests/unitary/with_extras/operator/test_files/job_container.yaml
  tests/unitary/with_extras/operator/test_files/job_python.yaml
  tests/unitary/with_extras/operator/test_files/local_container.yaml
  tests/unitary/with_extras/operator/test_files/local_python.yaml
Labels: OCA Verified

#389 Refactor LLM plugins.
  ads/llm/__init__.py
  ads/llm/langchain/plugins.py
  ads/llm/langchain/plugins/__init__.py
  ads/llm/langchain/plugins/base.py
  ads/llm/langchain/plugins/llm_gen_ai.py
  ads/llm/langchain/plugins/llm_md.py
Labels: OCA Verified

#391 Update ModelDeploymentTGI
  ads/llm/langchain/plugins/llm_md.py
Labels: OCA Verified

#393 Feature/feature store 1.0.4
  ads/feature_store/docs/requirements.txt
  ads/feature_store/docs/source/ads.feature_store.query.rst
  ads/feature_store/docs/source/feature_group.rst
  ads/feature_store/docs/source/feature_store.rst
  ads/feature_store/docs/source/feature_store_class.rst
  ads/feature_store/docs/source/index.rst
  ads/feature_store/docs/source/module.rst
  ads/feature_store/docs/source/quickstart.rst
  ads/feature_store/docs/source/release_notes.rst
  ads/feature_store/docs/source/terraform.rst
  ads/feature_store/docs/source/ui.rst
Labels: OCA Verified

#388 create archive when env yaml is provided in publish command
  ads/opctl/conda/cmds.py
  ads/opctl/conda/pack.py
Labels: OCA Verified

#392 Reduced horizon parameters and handled datetime error for AutoMLx model
  ads/opctl/operator/lowcode/forecast/model/arima.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/autots.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
  ads/opctl/operator/lowcode/forecast/model/prophet.py
  ads/opctl/operator/lowcode/forecast/operator_config.py
  ads/opctl/operator/lowcode/forecast/schema.yaml
  ads/opctl/operator/lowcode/forecast/utils.py
Labels: OCA Verified

#398 resolving autots models bug
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/autots.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/utils.py
  docs/source/user_guide/operators/forecasting_operator/examples.rst
Labels: OCA Verified
