Repository oracle/accelerated-data-science, pull requests merged in 2023-11, with the labels that each got.

#385 Odsc 46836/fix incomplete testdata issues
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/utils.py
  tests/unitary/with_extras/operator/forecast/test_model_base_model.py
Labels: OCA Verified

#401 ODSC-47050: Adds unit tests for the operator backends.
  ads/opctl/backend/ads_ml_job.py
  ads/opctl/backend/local.py
  tests/unitary/with_extras/operator/test_files/test_operator/MLoperator
  tests/unitary/with_extras/operator/test_operator_backend.py
Labels: OCA Verified

#402 Bugfix On Documentation
  docs/source/_static/logo-dark-mode.png
  docs/source/_static/logo-light-mode.png
Labels: bug, documentation, OCA Verified

#407 Feature/forecasting auto algorithm improvements
  ads/opctl/operator/lowcode/forecast/__main__.py
  ads/opctl/operator/lowcode/forecast/const.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/model/factory.py
  ads/opctl/operator/lowcode/forecast/model/forecast_datasets.py
  ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
  ads/opctl/operator/lowcode/forecast/model/prophet.py
  ads/opctl/operator/lowcode/forecast/operator_config.py
  ads/opctl/operator/lowcode/forecast/schema.yaml
  ads/opctl/operator/lowcode/forecast/utils.py
Labels: OCA Verified

#412 Bug Fix : Dropping target column if present in additional data
  ads/opctl/operator/lowcode/forecast/utils.py
Labels: OCA Verified

#410 ODSC-49028/sort by datetime col & ODSC-48265/training metrics mismatch
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/autots.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/model/transformations.py
  ads/opctl/operator/lowcode/forecast/utils.py
  tests/unitary/with_extras/operator/forecast/test_model_automlx.py
  tests/unitary/with_extras/operator/forecast/test_model_base_model.py
Labels: OCA Verified

#406 [ODSC-48857 | ODSC-48858] Global Explainability & Local Explainability - ARIMA
  ads/opctl/operator/lowcode/forecast/model/arima.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/autots.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/model/prophet.py
  ads/opctl/operator/lowcode/forecast/operator_config.py
  ads/opctl/operator/lowcode/forecast/schema.yaml
Labels: OCA Verified

#378 mlm upgrade to new version format
  ads/feature_store/dataset.py
  ads/feature_store/docs/source/release_notes.rst
  ads/feature_store/docs/source/transformation.rst
  ads/feature_store/execution_strategy/spark/spark_execution.py
  ads/feature_store/feature_group.py
  ads/feature_store/response/response_builder.py
  ads/feature_store/statistics/abs_feature_value.py
  ads/feature_store/statistics/charts/abstract_feature_plot.py
  ads/feature_store/statistics/charts/box_plot.py
  ads/feature_store/statistics/charts/frequency_distribution.py
  ads/feature_store/statistics/charts/probability_distribution.py
  ads/feature_store/statistics/charts/top_k_frequent_elements.py
  ads/feature_store/statistics/feature_stat.py
  ads/feature_store/statistics/generic_feature_value.py
  ads/feature_store/statistics/statistics.py
Labels: OCA Verified

#415 ODSC-49565/corrections in metrics calculation per horizon
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/utils.py
Labels: OCA Verified

#411 Update sorting logic when getting logs from OCI logging
  ads/common/oci_logging.py
Labels: OCA Verified

#405 ODSC-49489: Fix service conda environments PAR link.
  ads/common/utils.py
  ads/model/runtime/utils.py
Labels: OCA Verified

#417 added docs and updated version
  ads/feature_store/docs/source/conf.py
  ads/feature_store/docs/source/notebook.rst
  ads/feature_store/docs/source/release_notes.rst
  pyproject.toml
Labels: OCA Verified

#416 Update Docs to link to Github for sample notebooks
  docs/source/user_guide/apachespark/dataflow-spark-magic.rst
  docs/source/user_guide/configuration/authentication.rst
  docs/source/user_guide/configuration/autonomous_database.rst
  docs/source/user_guide/configuration/configuration.rst
  docs/source/user_guide/data_flow/dataflow.rst
  docs/source/user_guide/model_training/ads_tuner.rst
Labels: OCA Verified

#419 making the output formatting more consistent
  ads/opctl/config/merger.py
  ads/opctl/config/resolver.py
  ads/opctl/config/versioner.py
  ads/opctl/config/yaml_parsers/base.py
  ads/opctl/operator/cli.py
  ads/opctl/operator/common/operator_loader.py
  ads/opctl/operator/common/utils.py
  ads/opctl/operator/lowcode/forecast/__main__.py
  ads/opctl/operator/lowcode/forecast/const.py
  ads/opctl/operator/lowcode/forecast/model/arima.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/autots.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/model/forecast_datasets.py
  ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
  ads/opctl/operator/lowcode/forecast/model/prophet.py
  ads/opctl/operator/lowcode/forecast/model/transformations.py
  ads/opctl/operator/lowcode/forecast/utils.py
  docs/source/user_guide/operators/forecasting_operator/forecast.rst
Labels: OCA Verified

#422 Fix failing apt-get install in action for unit tests
  .github/workflows/run-unittests-py38-cov-report.yml
  .github/workflows/run-unittests-py39-py310.yml
  .github/workflows/test-env-setup/action.yml
  tests/unitary/with_extras/model/test_env_info.py
  tests/unitary/with_extras/opctl/test_opctl_conda.py
Labels: OCA Verified

#420 [ODSC-48861 | ODSC-48862] Add local, global explanation for the AutoTS model
  ads/opctl/operator/lowcode/forecast/model/autots.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
Labels: OCA Verified

#339 Fix integration tests to run with instance_principal
  ads/jobs/serializer.py
  ads/opctl/config/merger.py
  ads/opctl/utils.py
  tests/integration/jobs/test_dsc_job.py
  tests/integration/jobs/test_jobs_cli.py
  tests/integration/jobs/test_jobs_notebook.py
  tests/integration/jobs/test_jobs_notebook_runtime.py
  tests/integration/jobs/test_jobs_runs.py
  tests/integration/opctl/test_opctl_cli.py
  tests/integration/opctl/test_opctl_conda.py
  tests/integration/opctl/test_opctl_utils.py
  tests/integration/other/test_artifact_saving_data.py
  tests/integration/other/test_common_model_artifact_save.py
  tests/integration/other/test_dataflow.py
  tests/integration/other/test_dataset_factory_open.py
  tests/integration/other/test_export_generic.py
  tests/integration/other/test_hpo_tuner_artifact.py
  tests/integration/other/test_prepare_artifact.py
Labels: OCA Verified

#421 Fixed model deployment failed return value
  ads/model/deployment/model_deployment.py
  ads/model/generic_model.py
  ads/model/service/oci_datascience_model_deployment.py
  tests/unitary/default_setup/model_deployment/test_model_deployment.py
  tests/unitary/default_setup/model_deployment/test_model_deployment_v2.py
  tests/unitary/with_extras/model/test_generic_model.py
Labels: OCA Verified

#381 [ODSC-48942]opctl create/publish error on M1 and M2
  THIRD_PARTY_LICENSES.txt
  ads/opctl/conda/cmds.py
  ads/opctl/conda/pack.py
  ads/opctl/docker/Dockerfile.job
  ads/opctl/utils.py
  pyproject.toml
Labels: OCA Verified

#395 PII operator.
  ads/common/decorator/runtime_dependency.py
  ads/data_labeling/mixin/data_labeling.py
  ads/opctl/operator/cmd.py
  ads/opctl/operator/common/operator_yaml_generator.py
  ads/opctl/operator/lowcode/pii/MLoperator
  ads/opctl/operator/lowcode/pii/README.md
  ads/opctl/operator/lowcode/pii/__init__.py
  ads/opctl/operator/lowcode/pii/__main__.py
  ads/opctl/operator/lowcode/pii/cmd.py
  ads/opctl/operator/lowcode/pii/constant.py
  ads/opctl/operator/lowcode/pii/environment.yaml
  ads/opctl/operator/lowcode/pii/errors.py
  ads/opctl/operator/lowcode/pii/model/__init__.py
  ads/opctl/operator/lowcode/pii/model/factory.py
  ads/opctl/operator/lowcode/pii/model/guardrails.py
  ads/opctl/operator/lowcode/pii/model/pii.py
  ads/opctl/operator/lowcode/pii/model/processor/__init__.py
  ads/opctl/operator/lowcode/pii/model/processor/email_replacer.py
  ads/opctl/operator/lowcode/pii/model/processor/mbi_replacer.py
  ads/opctl/operator/lowcode/pii/model/processor/name_replacer.py
  ads/opctl/operator/lowcode/pii/model/processor/number_replacer.py
  ads/opctl/operator/lowcode/pii/model/processor/remover.py
  ads/opctl/operator/lowcode/pii/model/report.py
  ads/opctl/operator/lowcode/pii/operator_config.py
  ads/opctl/operator/lowcode/pii/schema.yaml
  ads/opctl/operator/lowcode/pii/utils.py
  dev-requirements.txt
  docs/source/index.rst
  docs/source/user_guide/operators/pii_operator/examples.rst
  docs/source/user_guide/operators/pii_operator/getting_started.rst
  docs/source/user_guide/operators/pii_operator/index.rst
  docs/source/user_guide/operators/pii_operator/install.rst
  docs/source/user_guide/operators/pii_operator/pii.rst
  docs/source/user_guide/operators/pii_operator/yaml_schema.rst
  pyproject.toml
  tests/unitary/with_extras/operator/pii/__init__.py
  tests/unitary/with_extras/operator/pii/test_factory.py
  tests/unitary/with_extras/operator/pii/test_files/__init__.py
  tests/unitary/with_extras/operator/pii/test_files/pii_test.yaml
  tests/unitary/with_extras/operator/pii/test_files/test_data.csv
  tests/unitary/with_extras/operator/pii/test_guardrail.py
  tests/unitary/with_extras/operator/pii/test_pii_scrubber.py
Labels: enhancement, OCA Verified, new feature

#418 ODSC-49703: Move the ADS config errors into debug level.
  ads/opctl/config/merger.py
  ads/opctl/operator/lowcode/forecast/MLoperator
Labels: OCA Verified

#430 Fixing test for pii operator
  ads/opctl/operator/lowcode/pii/README.md
  ads/opctl/operator/lowcode/pii/environment.yaml
  docs/source/user_guide/operators/pii_operator/getting_started.rst
  docs/source/user_guide/operators/pii_operator/install.rst
  docs/source/user_guide/operators/pii_operator/pii.rst
  docs/source/user_guide/operators/pii_operator/yaml_schema.rst
  pyproject.toml
  tests/unitary/with_extras/operator/pii/test_factory.py
Labels: OCA Verified

#436 ADS release 2.9.0
  .github/workflows/run-unittests-py38-cov-report.yml
  .github/workflows/run-unittests-py39-py310.yml
  dev-requirements.txt
  docs/source/release_notes.rst
  pyproject.toml
Labels: OCA Verified

#439 Feature/ad
  ads/opctl/operator/lowcode/anomaly/schema.yaml
Labels: OCA Verified

#440 Fs bug fix
  ads/feature_store/docs/requirements.txt
  ads/feature_store/docs/source/index.rst
  ads/feature_store/docs/source/notebook.rst
  ads/feature_store/docs/source/overview.rst
  ads/feature_store/docs/source/quickstart.rst
  ads/feature_store/docs/source/release_notes.rst
  tests/integration/feature_store/test_as_of_for_featuregroup_and_dataset.py
  tests/integration/feature_store/test_base.py
Labels: OCA Verified

#442 Added changes to operator
  ads/feature_store/docs/requirements.txt
  ads/feature_store/docs/source/index.rst
  ads/feature_store/docs/source/notebook.rst
  ads/feature_store/docs/source/overview.rst
  ads/feature_store/docs/source/quickstart.rst
  ads/feature_store/docs/source/release_notes.rst
  tests/integration/feature_store/test_as_of_for_featuregroup_and_dataset.py
  tests/integration/feature_store/test_base.py
Labels: OCA Verified

#446 Feature/ad
  ads/opctl/operator/lowcode/anomaly/__main__.py
  ads/opctl/operator/lowcode/anomaly/model/anomaly_dataset.py
  ads/opctl/operator/lowcode/anomaly/model/autots.py
  ads/opctl/operator/lowcode/anomaly/model/base_model.py
  ads/opctl/operator/lowcode/anomaly/model/factory.py
  ads/opctl/operator/lowcode/anomaly/operator_config.py
  ads/opctl/operator/lowcode/anomaly/schema.yaml
  ads/opctl/operator/lowcode/anomaly/utils.py
  tests/unitary/default_setup/opctl/__init__.py
  tests/unitary/default_setup/opctl/test_anomaly_extensive.py
  tests/unitary/default_setup/opctl/test_anomaly_simple.py
Labels: OCA Verified

#450 Fixes init yaml formatting for AD operator
  ads/opctl/operator/lowcode/anomaly/cmd.py
Labels: OCA Verified

#455 adding integration tests
  ads/opctl/operator/lowcode/anomaly/schema.yaml
  tests/unitary/default_setup/opctl/test_anomaly_simple.py
Labels: OCA Verified

#445 Fix/serialization of llm plugins
  ads/llm/langchain/plugins/base.py
  ads/llm/langchain/plugins/contant.py
  ads/llm/langchain/plugins/llm_gen_ai.py
  ads/llm/langchain/plugins/llm_md.py
  ads/llm/serialize.py
Labels: OCA Verified

#451 BugFix/typo in documentation
  ads/common/auth.py
  docs/source/user_guide/cli/authentication.rst
  tests/unitary/default_setup/auth/test_auth.py
  tests/unitary/default_setup/telemetry/test_agent.py
Labels: bug, documentation, OCA Verified

#459 Updated autots _build_model
  ads/opctl/operator/lowcode/anomaly/model/autots.py
Labels: OCA Verified

#456 ODSC-50353: Allow to override the config values in the operator specification
  ads/opctl/config/merger.py
  ads/opctl/constants.py
  ads/opctl/decorator/common.py
  ads/opctl/operator/cli.py
  ads/opctl/operator/cmd.py
  ads/opctl/operator/common/backend_factory.py
  ads/opctl/operator/common/dictionary_merger.py
  tests/unitary/with_extras/operator/test_common_dictionary_merger.py
Labels: OCA Verified

#457 Fix version of lightgbm to be <4.0.0
  .github/workflows/run-unittests-py38-cov-report.yml
  .github/workflows/run-unittests-py39-py310.yml
  pyproject.toml
  test-requirements.txt
  tests/unitary/default_setup/telemetry/test_agent.py
Labels: OCA Verified
