Repository oracle/accelerated-data-science, pull requests merged in 2023-05, with the labels that each got.

#159 Add information about AuthContext context class with link to api doc
  .github/workflows/publish-to-readthedocs.yml
  .github/workflows/run-unittests-default_setup.yml
  .github/workflows/run-unittests.yml
  docs/source/user_guide/configuration/authentication.rst
Labels: OCA Verified

#165 Update ads CLI to explicitly use python3
  ads/ads
Labels: OCA Verified

#160 Add GPU Deployments section to score.rst
  docs/source/user_guide/model_registration/_template/score.rst
Labels: OCA Verified

#134 ODSC 29065/Model Deployment opctl for local dev
  ads/model/deployment/model_deployment.py
  ads/opctl/backend/ads_model_deployment.py
  ads/opctl/backend/base.py
  ads/opctl/backend/local.py
  ads/opctl/cli.py
  ads/opctl/cmds.py
  ads/opctl/conda/cmds.py
  ads/opctl/constants.py
  ads/opctl/model/__init__.py
  ads/opctl/model/cli.py
  ads/opctl/model/cmds.py
  ads/opctl/script.py
  tests/unitary/with_extras/opctl/test_opctl_local_model_deployment_backend.py
  tests/unitary/with_extras/opctl/test_opctl_model.py
  tests/unitary/with_extras/opctl/test_opctl_model_deployment_backend.py
Labels: OCA Verified

#164 Update unit tests to set compartment ID if it is not available from environment variables.
  .github/workflows/run-unittests-default_setup.yml
  .github/workflows/run-unittests.yml
  tests/unitary/default_setup/auth/test_auth.py
  tests/unitary/default_setup/catalog/test_catalog_notebook.py
  tests/unitary/default_setup/catalog/test_catalog_project.py
  tests/unitary/with_extras/vault/test_vault_vault.py
Labels: OCA Verified

#167 Support setting "defined tags" in data science jobs.
  ads/jobs/ads_job.py
  ads/jobs/builders/infrastructure/base.py
  ads/jobs/builders/infrastructure/dsc_job.py
  ads/jobs/builders/infrastructure/dsc_job_runtime.py
  ads/jobs/builders/runtimes/base.py
  tests/unitary/default_setup/jobs/test_jobs_base.py
  tests/unitary/default_setup/jobs/test_jobs_tags.py
Labels: OCA Verified

#162 Modified ADS dataset class
  ads/dataset/classification_dataset.py
  ads/dataset/dataset.py
  ads/dataset/dataset_with_target.py
  ads/dataset/forecasting_dataset.py
  ads/dataset/helper.py
  ads/dataset/regression_dataset.py
  docs/source/user_guide/data_transformation/data_transformation.rst
  docs/source/user_guide/loading_data/connect.rst
  docs/source/user_guide/loading_data/connect_legacy.rst
  docs/source/user_guide/loading_data/supported_format.rst
  docs/source/user_guide/model_catalog/model_catalog.rst
  docs/source/user_guide/quickstart/quickstart.rst
  tests/unitary/with_extras/dataset/data/orcl_attrition.csv
  tests/unitary/with_extras/dataset/test_dataset_dataset.py
  tests/unitary/with_extras/dataset/test_dataset_target.py
Labels: OCA Verified

#161 ODSC-37692:[MLFlow][Projects] Improve ADS OPCTL to be able to generat…
  .pre-commit-config.yaml
  ads/__init__.py
  ads/cli.py
  ads/common/extended_enum.py
  ads/common/serializer.py
  ads/jobs/ads_job.py
  ads/jobs/builders/base.py
  ads/jobs/builders/infrastructure/dataflow.py
  ads/jobs/builders/infrastructure/dsc_job.py
  ads/jobs/builders/runtimes/base.py
  ads/jobs/builders/runtimes/container_runtime.py
  ads/jobs/builders/runtimes/python_runtime.py
  ads/jobs/schema/runtime_schema.json
  ads/jobs/serializer.py
  ads/model/deployment/model_deployment.py
  ads/model/deployment/model_deployment_infrastructure.py
  ads/model/deployment/model_deployment_runtime.py
  ads/model/model_version_set.py
  ads/opctl/backend/ads_dataflow.py
  ads/opctl/backend/ads_ml_job.py
  ads/opctl/backend/ads_ml_pipeline.py
  ads/opctl/backend/ads_model_deployment.py
  ads/opctl/backend/base.py
  ads/opctl/cli.py
  ads/opctl/cmds.py
  ads/opctl/config/merger.py
  ads/opctl/constants.py
  ads/pipeline/ads_pipeline.py
  ads/telemetry/telemetry.py
  tests/unitary/default_setup/model_deployment/test_model_deployment_v2.py
  tests/unitary/default_setup/pipeline/test_pipeline.py
  tests/unitary/default_setup/telemetry/test_agent.py
  tests/unitary/with_extras/opctl/test_files/dataflow_dataFlow.yaml
  tests/unitary/with_extras/opctl/test_files/dataflow_dataFlowNotebook.yaml
  tests/unitary/with_extras/opctl/test_files/job_container.yaml
  tests/unitary/with_extras/opctl/test_files/job_gitPython.yaml
  tests/unitary/with_extras/opctl/test_files/job_notebook.yaml
  tests/unitary/with_extras/opctl/test_files/job_python.yaml
  tests/unitary/with_extras/opctl/test_files/job_script.yaml
  tests/unitary/with_extras/opctl/test_files/modeldeployment_conda.yaml
  tests/unitary/with_extras/opctl/test_files/modeldeployment_container.yaml
  tests/unitary/with_extras/opctl/test_files/pipeline_container.yaml
  tests/unitary/with_extras/opctl/test_files/pipeline_gitPython.yaml
  tests/unitary/with_extras/opctl/test_files/pipeline_notebook.yaml
  tests/unitary/with_extras/opctl/test_files/pipeline_python.yaml
  tests/unitary/with_extras/opctl/test_files/pipeline_script.yaml
  tests/unitary/with_extras/opctl/test_opctl_cmds.py
  tests/unitary/with_extras/opctl/test_opctl_dataflow_backend.py
  tests/unitary/with_extras/opctl/test_opctl_ml_job_backend.py
  tests/unitary/with_extras/opctl/test_opctl_ml_pipeline_backend.py
  tests/unitary/with_extras/opctl/test_opctl_model_deployment_backend.py
Labels: OCA Verified

#166 ODSC-42082: Add usage of the `ads opctl init` to the ADS docs
  docs/Makefile
  docs/source/conf.py
  docs/source/user_guide/cli/opctl/configure.rst
Labels: OCA Verified

#152 ODSC-39731/support_running_sparkpipelinemodel_in_df
  ads/common/object_storage_details.py
  ads/common/utils.py
  ads/feature_engineering/schema.py
  ads/model/artifact.py
  ads/model/artifact_downloader.py
  ads/model/common/utils.py
  ads/model/framework/spark_model.py
  ads/model/generic_model.py
  ads/model/model_introspect.py
  ads/model/model_metadata.py
  ads/model/model_metadata_mixin.py
  ads/model/runtime/runtime_info.py
  ads/templates/score_pyspark.jinja2
  tests/unitary/default_setup/common/test_common_utils.py
  tests/unitary/default_setup/model/test_artifact_downloader.py
  tests/unitary/with_extras/model/test_artifact.py
Labels: OCA Verified

#83 Update mvs docs
  ads/dataflow/dataflow.py
  docs/source/user_guide/_template/prerequisite/data_flow.rst
  docs/source/user_guide/apachespark/dataflow.rst
  docs/source/user_guide/apachespark/setup-installation.rst
  docs/source/user_guide/cli/opctl/_template/monitoring.rst
  docs/source/user_guide/cli/opctl/configure.rst
  docs/source/user_guide/jobs/run_script.rst
  docs/source/user_guide/model_registration/introduction.rst
  docs/source/user_guide/quick_start/quick_start.rst
Labels: OCA Verified

#175 Release v2.8.4 - Main to Develop (docs changes)
  README.md
  docs/requirements.txt
  docs/source/_static/logo-dark-mode.png
  docs/source/_static/logo-light-mode.png
  docs/source/conf.py
  docs/source/index.rst
  docs/source/user_guide/apachespark/dataflow-spark-magic.rst
  docs/source/user_guide/apachespark/dataflow.rst
  docs/source/user_guide/apachespark/spark.rst
  docs/source/user_guide/cli/opctl/localdev/condapack.rst
  docs/source/user_guide/cli/quickstart.rst
  docs/source/user_guide/jobs/data_science_job.rst
  docs/source/user_guide/jobs/policies.rst
  docs/source/user_guide/jobs/run_container.rst
  docs/source/user_guide/jobs/run_git.rst
  docs/source/user_guide/loading_data/connect.rst
  docs/source/user_guide/loading_data/connect_legacy.rst
  docs/source/user_guide/model_registration/_template/deploy.rst
  docs/source/user_guide/model_training/automl/quick_start.rst
  docs/source/user_guide/model_training/distributed_training/configuration/configuration.rst
  docs/source/user_guide/model_training/distributed_training/dask/dask.rst
  docs/source/user_guide/model_training/distributed_training/developer/developer.rst
  docs/source/user_guide/model_training/distributed_training/overview.rst
  docs/source/user_guide/model_training/distributed_training/remote_source_code.rst
  docs/source/user_guide/pipeline/quick_start.rst
  docs/source/user_guide/quickstart/quickstart.rst
Labels: OCA Verified

#178 Revert accident changes in docs/../jobs/run_script.rst
  docs/source/user_guide/jobs/run_script.rst
Labels: OCA Verified

#163 Add 2.8.4 release notes.
  docs/source/release_notes.rst
Labels: OCA Verified

#179 Release v2.8.4 - Bump version
  .github/workflows/run-unittests-default_setup.yml
  .github/workflows/run-unittests.yml
  ads/ads_version.json
Labels: OCA Verified

#177 ODSC-29065/md_opctl_doc_new
  ads/opctl/backend/base.py
  ads/opctl/backend/local.py
  ads/opctl/cli.py
  ads/opctl/model/cmds.py
  ads/opctl/script.py
  docs/source/user_guide/cli/opctl/local-development-setup.rst
  docs/source/user_guide/cli/opctl/localdev/local_deployment.rst
  tests/unitary/with_extras/opctl/test_opctl_local_model_deployment_backend.py
  tests/unitary/with_extras/opctl/test_opctl_model.py
Labels: OCA Verified

#180 Release notes v2.8.4 - fixed the date
  docs/source/release_notes.rst
Labels: OCA Verified

#183 Spelling fixes
  docs/source/release_notes.rst
  docs/source/user_guide/apachespark/quickstart.rst
  docs/source/user_guide/jobs/data_science_job.rst
  docs/source/user_guide/jobs/overview.rst
  docs/source/user_guide/jobs/yaml_schema.rst
  docs/source/yaml_schema/jobs/job.html
  docs/source/yaml_schema/jobs/job.yaml
Labels: OCA Verified

#187 Hotfix for readthedocs builder
  .readthedocs.yaml
Labels: OCA Verified

#190 ODSC-39272. Fix for links of See API documentation
  docs/source/user_guide/cli/authentication.rst
  docs/source/user_guide/model_registration/frameworks/huggingfacemodel.rst
  docs/source/user_guide/model_registration/frameworks/lightgbmmodel.rst
  docs/source/user_guide/model_registration/frameworks/pytorchmodel.rst
  docs/source/user_guide/model_registration/frameworks/sklearnmodel.rst
  docs/source/user_guide/model_registration/frameworks/sparkpipelinemodel.rst
  docs/source/user_guide/model_registration/frameworks/tensorflowmodel.rst
  docs/source/user_guide/model_registration/frameworks/xgboostmodel.rst
Labels: OCA Verified

#169 Updated mounting file systems in job docs.
  docs/source/user_guide/jobs/infra_and_runtime.rst
  docs/source/user_guide/jobs/tabs/infra_config.rst
  docs/source/user_guide/jobs/tabs/quick_start_job.rst
Labels: OCA Verified

#168 Updated egress support in MD docs
  docs/source/user_guide/model_registration/model_deploy_byoc.rst
Labels: OCA Verified

#194 Update CONTRIBUTING.md with GitHub flow branching strategy.
  CONTRIBUTING.md
Labels: documentation, OCA Verified

#195 Remove ads.opctl.spec.
  ads/opctl/spec/__init__.py
  ads/opctl/spec/abstract_operator_spec.py
  ads/opctl/spec/operator_spec_factory.py
  ads/opctl/spec/utils.py
  docs/source/ads.opctl.rst
  docs/source/ads.opctl.spec.rst
Labels: OCA Verified

#173 Support creating ADSDataset through pandas accessor
  ads/dataset/dataset_with_target.py
  ads/dataset/mixin/__init__.py
  ads/dataset/mixin/dataset_accessor.py
  ads/feature_engineering/accessor/dataframe_accessor.py
  tests/unitary/with_extras/dataset/test_dataset_dataset.py
  tests/unitary/with_extras/dataset/test_dataset_target.py
Labels: OCA Verified

#192 Updated mounting file systems in job docs.
  docs/source/user_guide/jobs/infra_and_runtime.rst
  docs/source/user_guide/jobs/tabs/infra_config.rst
  docs/source/user_guide/jobs/tabs/quick_start_job.rst
Labels: OCA Verified

#199 Revert "Updated mounting file systems in job docs." (waiting service GA)
  docs/source/user_guide/jobs/infra_and_runtime.rst
  docs/source/user_guide/jobs/tabs/infra_config.rst
  docs/source/user_guide/jobs/tabs/quick_start_job.rst
Labels: documentation, OCA Verified, waiting service GA

#200 Minor update on Jobs API docs
  docs/source/user_guide/jobs/data_science_job.rst
  docs/source/user_guide/jobs/infra_and_runtime.rst
  docs/source/user_guide/jobs/policies.rst
  docs/source/user_guide/jobs/run_git.rst
  docs/source/user_guide/jobs/run_notebook.rst
  docs/source/user_guide/jobs/run_python.rst
  docs/source/user_guide/jobs/tabs/python_runtime.rst
  docs/source/user_guide/jobs/toc_local.rst
Labels: documentation, OCA Verified

#202 Fix api doc for `ads.common.utils.copy_file`
  ads/common/utils.py
Labels: bug, documentation, OCA Verified

#196 Fix API, that gives an error if target is not specified
  ads/dataset/dataset.py
  tests/unitary/with_extras/dataset/test_dataset_dataset.py
Labels: bug, OCA Verified

#193 Fixed suggested_sampling for imbalanced data in RecommendationTransformer
  ads/dataset/recommendation_transformer.py
  tests/unitary/with_extras/dataset/test_dataset_target.py
Labels: bug, OCA Verified

#198 Added support for private key content for set_auth()
  ads/common/auth.py
  docs/source/user_guide/cli/authentication.rst
  tests/unitary/default_setup/auth/test_auth.py
  tests/unitary/default_setup/telemetry/test_agent.py
  tests/unitary/with_extras/opctl/test_opctl_core_site.py
Labels: enhancement, OCA Verified, security

#203 ADS release notes v2.8.5
  ads/ads_version.json
  docs/source/release_notes.rst
  docs/source/user_guide/cli/quickstart.rst
  setup.py
Labels: OCA Verified

#207 Added support for overriding defined tags in ads job run.
  ads/jobs/ads_job.py
  ads/jobs/builders/infrastructure/dsc_job.py
Labels: bug, OCA Verified

#210 Added defined tags for data flow
  ads/jobs/builders/infrastructure/dataflow.py
  docs/source/user_guide/apachespark/dataflow.rst
  docs/source/user_guide/apachespark/quickstart.rst
  tests/unitary/default_setup/jobs/test_jobs_dataflow.py
Labels: bug, OCA Verified
