Repository oracle/accelerated-data-science, pull requests merged in 2024-01, with the labels that each got.

#510 Update Copyright Check for 2024 and Fix LangChain tests
  .pre-commit-config.yaml
  ads/llm/chain.py
  tests/unitary/with_extras/langchain/test_guardrails.py
  tests/unitary/with_extras/langchain/test_serialization.py
Labels: OCA Verified

#516 code fixes for transfrmation mode check
  ads/feature_store/common/utils/transformation_utils.py
  ads/feature_store/execution_strategy/spark/spark_execution.py
  ads/feature_store/feature_store.py
  ads/feature_store/transformation.py
Labels: OCA Verified

#515 Create dummy wrappers for AquaModel and AquaDeployment
  ads/aqua/__init__.py
  ads/aqua/deployment.py
  ads/aqua/model.py
  tests/unitary/with_extras/aqua/__init__.py
  tests/unitary/with_extras/aqua/test_deployment.py
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified

#500 Improved Progress Bar in Model Deployment and Model
  ads/common/oci_mixin.py
  ads/common/work_request.py
  ads/model/service/oci_datascience_model.py
  ads/model/service/oci_datascience_model_deployment.py
  tests/unitary/default_setup/common/test_work_request.py
  tests/unitary/default_setup/model/test_oci_datascience_model.py
  tests/unitary/default_setup/model_deployment/test_oci_datascience_model_deployment.py
Labels: OCA Verified

#483 Renames "runtime" on the "backend" in the operator merged specification
  ads/opctl/operator/cmd.py
  ads/opctl/operator/common/backend_factory.py
  ads/opctl/operator/common/const.py
  ads/opctl/operator/common/operator_config.py
Labels: OCA Verified

#517 Subsampling data for faster plot rendering
  ads/opctl/operator/lowcode/forecast/const.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/utils.py
Labels: OCA Verified

#511 Forecasting model parallelization
  ads/opctl/operator/lowcode/forecast/model/arima.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
  ads/opctl/operator/lowcode/forecast/model/prophet.py
  ads/opctl/operator/lowcode/forecast/operator_config.py
Labels: OCA Verified

#518 Historical fitted values for the AutoTS model
  ads/opctl/operator/lowcode/forecast/model/autots.py
Labels: OCA Verified

#488 ODSC-34939: Implement optional loading of artifacts in the GenericModel
  ads/model/generic_model.py
  tests/unitary/with_extras/model/test_generic_model.py
Labels: OCA Verified

#514 Bugfix/fetch ds endpoint in mixin
  ads/common/oci_datascience.py
  ads/common/oci_mixin.py
  tests/unitary/with_extras/model/test_generic_model.py
Labels: OCA Verified

#521 Fixed artifact dir
  ads/model/artifact_downloader.py
Labels: OCA Verified

#522 ODSC-34939: Cleanup Summary Status Updates
  ads/model/generic_model.py
Labels: OCA Verified

#513 Support Running Any Command in PyTorchDistributed Runtime
  ads/jobs/templates/driver_pytorch.py
  ads/jobs/templates/driver_utils.py
Labels: OCA Verified

#523 Update Generative AI LLM model to use new APIs.
  ads/llm/langchain/plugins/base.py
  ads/llm/langchain/plugins/contant.py
  ads/llm/langchain/plugins/embeddings.py
  ads/llm/langchain/plugins/llm_gen_ai.py
  docs/source/user_guide/large_language_model/index.rst
  docs/source/user_guide/large_language_model/langchain_models.rst
  docs/source/user_guide/large_language_model/retrieval.rst
Labels: OCA Verified

#524 Add Fire CLI
  ads/aqua/__init__.py
  ads/aqua/deployment.py
  ads/aqua/fine_tune.py
  ads/aqua/job.py
  ads/aqua/model.py
  ads/cli.py
Labels: OCA Verified

#528 AQUA JupyterLab Extension Example
  ads/aqua/__init__.py
  ads/aqua/base.py
  ads/aqua/deployment.py
  ads/aqua/extension/__init__.py
  ads/aqua/extension/base_handler.py
  ads/aqua/extension/job_handler.py
  ads/aqua/extension/model_handler.py
  ads/aqua/fine_tune.py
  ads/aqua/job.py
  ads/aqua/model.py
Labels: OCA Verified

#526 added validation data metrics and updated report, inliers, outliers generation
  ads/opctl/operator/lowcode/anomaly/const.py
  ads/opctl/operator/lowcode/anomaly/model/anomaly_dataset.py
  ads/opctl/operator/lowcode/anomaly/model/automlx.py
  ads/opctl/operator/lowcode/anomaly/model/autots.py
  ads/opctl/operator/lowcode/anomaly/model/base_model.py
  ads/opctl/operator/lowcode/anomaly/model/tods.py
  ads/opctl/operator/lowcode/anomaly/operator_config.py
  ads/opctl/operator/lowcode/anomaly/schema.yaml
  ads/opctl/operator/lowcode/anomaly/utils.py
Labels: OCA Verified

#512 Model parameters and pickle generation, reloading of model pickle
  ads/opctl/operator/lowcode/forecast/model/arima.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/autots.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
  ads/opctl/operator/lowcode/forecast/model/prophet.py
  ads/opctl/operator/lowcode/forecast/operator_config.py
  ads/opctl/operator/lowcode/forecast/schema.yaml
  ads/opctl/operator/lowcode/forecast/utils.py
Labels: OCA Verified

#531 Feature/anomaly detect
  ads/opctl/operator/cmd.py
  ads/opctl/operator/common/utils.py
  ads/opctl/operator/lowcode/anomaly/MLoperator
  ads/opctl/operator/lowcode/anomaly/README.md
  ads/opctl/operator/lowcode/anomaly/__init__.py
  ads/opctl/operator/lowcode/anomaly/__main__.py
  ads/opctl/operator/lowcode/anomaly/cmd.py
  ads/opctl/operator/lowcode/anomaly/const.py
  ads/opctl/operator/lowcode/anomaly/environment.yaml
  ads/opctl/operator/lowcode/anomaly/model/__init__.py
  ads/opctl/operator/lowcode/anomaly/model/anomaly_dataset.py
  ads/opctl/operator/lowcode/anomaly/model/automlx.py
  ads/opctl/operator/lowcode/anomaly/model/autots.py
  ads/opctl/operator/lowcode/anomaly/model/base_model.py
  ads/opctl/operator/lowcode/anomaly/model/factory.py
  ads/opctl/operator/lowcode/anomaly/model/tods.py
  ads/opctl/operator/lowcode/anomaly/operator_config.py
  ads/opctl/operator/lowcode/anomaly/schema.yaml
  ads/opctl/operator/lowcode/anomaly/utils.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/utils.py
  pyproject.toml
  tests/operators/anomaly/__init__.py
  tests/operators/anomaly/test_anomaly_extensive.py
  tests/operators/anomaly/test_anomaly_simple.py
  tests/operators/forecast/test_datasets.py
  tests/unitary/default_setup/telemetry/test_agent.py
Labels: OCA Verified

#534 Fixed horizon while generating forecast.yaml
  ads/opctl/operator/lowcode/forecast/schema.yaml
Labels: OCA Verified

#530 YAML Inputs for Anomaly Detection
  ads/opctl/operator/lowcode/anomaly/schema.yaml
  tests/operators/anomaly/test_anomaly_simple.py
Labels: OCA Verified

#535 [ODSC-51508] : Fix/forecast v2 for tmp folder
  ads/opctl/operator/lowcode/forecast/model/base_model.py
Labels: OCA Verified

#527 Fixed duplicated logs in Model Deployment
  ads/common/oci_logging.py
Labels: OCA Verified

#538 ODSC-51434/List model API
  ads/aqua/base.py
  ads/aqua/model.py
Labels: OCA Verified, AQUA

#539 Added dummy aqua response for get/list
  ads/aqua/deployment.py
  ads/aqua/model.py
Labels: OCA Verified

#541 aqua/fix/hardcoded list
  ads/aqua/model.py
Labels: OCA Verified, AQUA

#520 Fixed llm docs.
  .github/workflows/run-unittests-default_setup.yml
  .github/workflows/run-unittests-py38-cov-report.yml
  .github/workflows/run-unittests-py39-py310.yml
  docs/source/user_guide/_template/distributed_training_policies.rst
  docs/source/user_guide/jobs/tabs/run_job.rst
  docs/source/user_guide/large_language_model/training_llm.rst
Labels: OCA Verified

#508 fix the imports
  docs/source/user_guide/large_language_model/retrieval.rst
  tests/integration/other/hpo_tuner_test_files/customized_model.py
Labels: OCA Verified

#542 ADS release v2.10.0
  docs/source/release_notes.rst
  pyproject.toml
Labels: OCA Verified

#543 AQUA/fix/Replaced hardcoded function with real implementation
  ads/aqua/model.py
Labels: OCA Verified, AQUA

#536 Anomaly: Added support for >1 target category columns
  ads/opctl/operator/lowcode/anomaly/model/anomaly_dataset.py
  ads/opctl/operator/lowcode/anomaly/model/automlx.py
  ads/opctl/operator/lowcode/anomaly/model/autots.py
  ads/opctl/operator/lowcode/anomaly/model/base_model.py
  ads/opctl/operator/lowcode/anomaly/model/tods.py
  ads/opctl/operator/lowcode/anomaly/utils.py
Labels: OCA Verified

#537 Forecasting: target_col removal from outputs, fixed prophet and autots bugs
  ads/opctl/operator/lowcode/forecast/model/arima.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/autots.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
  ads/opctl/operator/lowcode/forecast/model/prophet.py
  ads/opctl/operator/lowcode/forecast/utils.py
Labels: OCA Verified

#547 Create dummy data
  ads/aqua/deployment.py
  ads/aqua/dummy_data/icon.txt
  ads/aqua/dummy_data/oci_model_deployments.json
  ads/aqua/dummy_data/oci_models.json
  ads/aqua/dummy_data/readme.md
  ads/aqua/model.py
Labels: OCA Verified

#557 Added endpoint for dummy md.
  ads/aqua/deployment.py
Labels: OCA Verified

#529 Uptake bokeh and fix ADS BokehHeatMap
  ads/dataset/correlation_plot.py
  pyproject.toml
  tests/unitary/default_setup/telemetry/test_agent.py
  tests/unitary/with_extras/dataset/test_dataset_correlation_plot.py
Labels: bug, OCA Verified, ready for review

#551 [ODSC 51354] Create new Aqua deployment
  ads/aqua/deployment.py
  ads/aqua/dummy_data/oci_model_deployments.json
  ads/aqua/extension/__init__.py
  ads/aqua/extension/base_handler.py
  ads/aqua/extension/deployment_handler.py
  ads/aqua/model.py
  ads/cli.py
Labels: OCA Verified
