Repository oracle/accelerated-data-science, pull requests merged in 2024-05, with the labels that each got.

#813 Improves the extraction of custom metadata items by key.
  ads/model/model_metadata.py
  tests/unitary/default_setup/model/test_model_metadata.py
Labels: OCA Verified

#810 AQUA CLI: Improve handling error and Add new flags
  ads/aqua/cli.py
  ads/aqua/exception.py
  ads/cli.py
  tests/unitary/with_extras/aqua/test_cli.py
Labels: OCA Verified, ready for review

#814 Updates on Job Run API
  ads/jobs/builders/infrastructure/dsc_job.py
  tests/unitary/default_setup/jobs/test_jobs_run.py
Labels: OCA Verified

#812 BYOM Model support
  THIRD_PARTY_LICENSES.txt
  ads/aqua/data.py
  ads/aqua/deployment.py
  ads/aqua/finetune.py
  ads/aqua/model.py
  ads/aqua/utils.py
  ads/config.py
  pyproject.toml
Labels: OCA Verified

#818 Odsc-56003/fix eval delete
  ads/aqua/evaluation.py
  tests/unitary/with_extras/aqua/test_evaluation.py
Labels: OCA Verified, ready for review, AQUA

#823 Adds id property to ModelDeployment class.
  ads/model/deployment/model_deployment.py
Labels: OCA Verified

#822 test cases for import models
  ads/aqua/constants.py
  ads/aqua/deployment.py
  ads/aqua/model.py
  ads/aqua/utils.py
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified

#815 Update model description attribute map
  ads/model/datascience_model.py
Labels: OCA Verified

#824 Add ready_to_import for list API
  ads/aqua/constants.py
  ads/aqua/data.py
  ads/aqua/model.py
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified

#757 Websocket handlers for AQUA
  ads/aqua/decorator.py
  ads/aqua/extension/__init__.py
  ads/aqua/extension/aqua_ws_msg_handler.py
  ads/aqua/extension/evaluation_ws_msg_handler.py
  ads/aqua/extension/models/__init__.py
  ads/aqua/extension/models/ws_models.py
  ads/aqua/extension/ui_websocket_handler.py
  ads/common/serializer.py
  ads/config.py
  tests/unitary/with_extras/aqua/test_ui_websocket_handler.py
Labels: OCA Verified

#798 Updated docs for Ray
  docs/source/user_guide/model_training/distributed_training/ray/creating.rst
  docs/source/user_guide/model_training/distributed_training/ray/ray.rst
Labels: OCA Verified

#826 AQUA Fetch HF Model Details
  ads/aqua/extension/common_handler.py
  ads/aqua/extension/model_handler.py
  ads/aqua/model.py
  tests/unitary/with_extras/aqua/test_model_handler.py
Labels: OCA Verified

#829 Add support for CLI generation
  ads/aqua/base.py
  ads/aqua/extension/model_handler.py
  ads/aqua/extension/ui_handler.py
  ads/aqua/model.py
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified

#830 Adds a handler to list service containers.
  ads/aqua/extension/model_handler.py
  ads/aqua/extension/ui_handler.py
  ads/aqua/model.py
  ads/aqua/ui.py
  tests/unitary/with_extras/aqua/test_data/ui/container_index.json
  tests/unitary/with_extras/aqua/test_model_handler.py
  tests/unitary/with_extras/aqua/test_ui.py
  tests/unitary/with_extras/aqua/test_ui_handler.py
Labels: OCA Verified

#827 Updated Fine Tuning Parameters
  ads/aqua/finetune.py
  tests/unitary/with_extras/aqua/test_finetuning.py
Labels: OCA Verified

#831 Get default configurations for Model Deployment
  ads/aqua/data.py
  ads/aqua/deployment.py
  ads/aqua/extension/deployment_handler.py
  tests/unitary/with_extras/aqua/test_deployment.py
Labels: OCA Verified

#833 Modelcard for shadow models
  ads/aqua/model.py
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified

#835 AQUA. Adds additional fields into the AquaModel class.
  ads/aqua/extension/model_handler.py
  ads/aqua/model.py
  ads/aqua/utils.py
  tests/unitary/with_extras/aqua/test_model.py
  tests/unitary/with_extras/aqua/test_model_handler.py
Labels: OCA Verified

#834 Get default configurations for Model FineTuning
  ads/aqua/extension/finetune_handler.py
  ads/aqua/finetune.py
  tests/unitary/with_extras/aqua/test_data/finetuning/ft_config.json
  tests/unitary/with_extras/aqua/test_finetuning.py
  tests/unitary/with_extras/aqua/test_finetuning_handler.py
Labels: OCA Verified

#836 freeze version of report-creator
  pyproject.toml
Labels: OCA Verified

#839 Update get and list model API
  ads/aqua/extension/model_handler.py
  ads/aqua/model.py
  tests/unitary/with_extras/aqua/test_model_handler.py
Labels: OCA Verified

#832 BUG: Fallback model referencing target series rather than the target column
  ads/opctl/operator/lowcode/anomaly/model/base_model.py
Labels: OCA Verified

#838 Fix AQUA tests
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified

#842 Fix UI handler and deployment tests
  tests/unitary/with_extras/aqua/test_data/ui/container_index.json
  tests/unitary/with_extras/aqua/test_deployment.py
  tests/unitary/with_extras/aqua/test_ui_handler.py
Labels: OCA Verified

#841 Extend GH Actions timeout
  .github/workflows/run-unittests-py38-cov-report.yml
  .github/workflows/run-unittests-py39-py310.yml
Labels: OCA Verified

#837 Aqua/refactor - reorganize code
  ads/aqua/__init__.py
  ads/aqua/app.py
  ads/aqua/cli.py
  ads/aqua/common/__init__.py
  ads/aqua/common/decorator.py
  ads/aqua/common/enums.py
  ads/aqua/common/errors.py
  ads/aqua/common/utils.py
  ads/aqua/config/config.py
  ads/aqua/constants.py
  ads/aqua/evaluation/__init__.py
  ads/aqua/evaluation/constants.py
  ads/aqua/evaluation/entities.py
  ads/aqua/evaluation/errors.py
  ads/aqua/evaluation/evaluation.py
  ads/aqua/extension/aqua_ws_msg_handler.py
  ads/aqua/extension/common_handler.py
  ads/aqua/extension/deployment_handler.py
  ads/aqua/extension/evaluation_handler.py
  ads/aqua/extension/evaluation_ws_msg_handler.py
  ads/aqua/extension/finetune_handler.py
  ads/aqua/extension/model_handler.py
  ads/aqua/extension/models/ws_models.py
  ads/aqua/extension/ui_handler.py
  ads/aqua/extension/ui_websocket_handler.py
  ads/aqua/finetuning/__init__.py
  ads/aqua/finetuning/constants.py
  ads/aqua/finetuning/entities.py
  ads/aqua/finetuning/finetuning.py
  ads/aqua/model.py
  ads/aqua/modeldeployment/__init__.py
  ads/aqua/modeldeployment/deployment.py
  ads/aqua/modeldeployment/entities.py
  ads/aqua/modeldeployment/inference.py
  ads/aqua/ui.py
  tests/unitary/with_extras/aqua/test_cli.py
  tests/unitary/with_extras/aqua/test_common_handler.py
  tests/unitary/with_extras/aqua/test_decorator.py
  tests/unitary/with_extras/aqua/test_deployment.py
  tests/unitary/with_extras/aqua/test_deployment_handler.py
  tests/unitary/with_extras/aqua/test_evaluation.py
  tests/unitary/with_extras/aqua/test_evaluation_handler.py
  tests/unitary/with_extras/aqua/test_finetuning.py
  tests/unitary/with_extras/aqua/test_finetuning_handler.py
  tests/unitary/with_extras/aqua/test_handlers.py
  tests/unitary/with_extras/aqua/test_model.py
  tests/unitary/with_extras/aqua/test_ui.py
  tests/unitary/with_extras/aqua/test_ui_handler.py
  tests/unitary/with_extras/aqua/test_utils.py
Labels: OCA Verified

#844 check if HF model input during register is available as shadow model
  ads/aqua/extension/model_handler.py
  ads/aqua/model.py
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified

#847 Aqua refactor: Use ExtendedEnumMeta only
  ads/aqua/app.py
  ads/aqua/common/enums.py
  ads/aqua/common/errors.py
  ads/aqua/common/utils.py
  ads/aqua/constants.py
  ads/aqua/data.py
  ads/aqua/evaluation/constants.py
  ads/aqua/evaluation/evaluation.py
  ads/aqua/extension/models/ws_models.py
  ads/aqua/extension/ui_handler.py
  ads/aqua/finetuning/constants.py
  ads/aqua/finetuning/finetuning.py
  ads/aqua/model.py
  ads/aqua/modeldeployment/deployment.py
  ads/aqua/modeldeployment/entities.py
  ads/aqua/ui.py
  tests/unitary/with_extras/aqua/test_evaluation.py
  tests/unitary/with_extras/aqua/test_finetuning.py
  tests/unitary/with_extras/aqua/test_ui_handler.py
Labels: OCA Verified

#846 Fix model module
  ads/aqua/extension/model_handler.py
  ads/aqua/extension/models/ws_models.py
  ads/aqua/extension/ui_handler.py
  ads/aqua/model/__init__.py
  ads/aqua/model/constants.py
  ads/aqua/model/entities.py
  ads/aqua/model/model.py
  ads/aqua/modeldeployment/deployment.py
  ads/aqua/modeldeployment/entities.py
  tests/unitary/with_extras/aqua/test_finetuning.py
  tests/unitary/with_extras/aqua/test_model.py
  tests/unitary/with_extras/aqua/test_model_handler.py
Labels: OCA Verified

#848 Aqua refactor: Move all enums under `enums.py` for centralized management
  ads/aqua/app.py
  ads/aqua/common/enums.py
  ads/aqua/common/utils.py
  ads/aqua/constants.py
  ads/aqua/data.py
  ads/aqua/evaluation/evaluation.py
  ads/aqua/extension/model_handler.py
  ads/aqua/extension/ui_handler.py
  ads/aqua/finetuning/finetuning.py
  ads/aqua/job.py
  ads/aqua/model/constants.py
  ads/aqua/model/entities.py
  ads/aqua/model/enums.py
  ads/aqua/model/model.py
  ads/aqua/modeldeployment/deployment.py
  ads/aqua/modeldeployment/entities.py
  ads/aqua/modeldeployment/enums.py
  ads/aqua/ui.py
  tests/unitary/with_extras/aqua/test_evaluation.py
  tests/unitary/with_extras/aqua/test_ui_handler.py
Labels: OCA Verified

#849 Aqua refactor: use const in aqua.constants.py
  ads/aqua/app.py
  ads/aqua/common/utils.py
  ads/aqua/constants.py
  ads/aqua/evaluation/evaluation.py
  ads/aqua/finetuning/finetuning.py
  ads/aqua/model/model.py
  ads/aqua/modeldeployment/deployment.py
  ads/aqua/modeldeployment/entities.py
  tests/unitary/with_extras/aqua/test_common_handler.py
  tests/unitary/with_extras/aqua/test_evaluation.py
Labels: OCA Verified

#845 Validate FT and MD parameter overrides
  ads/aqua/common/utils.py
  ads/aqua/extension/deployment_handler.py
  ads/aqua/extension/finetune_handler.py
  ads/aqua/finetuning/finetuning.py
  ads/aqua/modeldeployment/constants.py
  ads/aqua/modeldeployment/deployment.py
  tests/unitary/with_extras/aqua/test_data/ui/container_index.json
  tests/unitary/with_extras/aqua/test_deployment.py
  tests/unitary/with_extras/aqua/test_deployment_handler.py
  tests/unitary/with_extras/aqua/test_finetuning.py
  tests/unitary/with_extras/aqua/test_finetuning_handler.py
Labels: OCA Verified

#850 Finetuning and MD default params dict
  ads/aqua/finetuning/finetuning.py
  ads/aqua/modeldeployment/deployment.py
  tests/unitary/with_extras/aqua/test_deployment.py
  tests/unitary/with_extras/aqua/test_finetuning.py
Labels: OCA Verified

#853 Add source model tag to imported models
  ads/aqua/extension/model_handler.py
  ads/aqua/model/model.py
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified

#854 Aqua refactor: move common dataclass into data.py
  ads/aqua/data.py
  ads/aqua/evaluation/entities.py
  ads/aqua/finetuning/entities.py
  ads/aqua/job.py
Labels: OCA Verified

#855 Aqua refactor: improvement on evaluation.py
  ads/aqua/common/enums.py
  ads/aqua/evaluation/constants.py
  ads/aqua/evaluation/evaluation.py
Labels: OCA Verified

#856 Minor changes for Verified Models
  ads/aqua/extension/model_handler.py
  ads/aqua/model/model.py
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified

#857 Fix version of HF hub in ads
  ads/aqua/model/model.py
  pyproject.toml
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified

#825 Feature/forecast auto select
  ads/opctl/operator/lowcode/anomaly/model/base_model.py
  ads/opctl/operator/lowcode/anomaly/operator_config.py
  ads/opctl/operator/lowcode/common/transformations.py
  ads/opctl/operator/lowcode/common/utils.py
  ads/opctl/operator/lowcode/forecast/__main__.py
  ads/opctl/operator/lowcode/forecast/const.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/model/factory.py
  ads/opctl/operator/lowcode/forecast/model_evaluator.py
  ads/opctl/operator/lowcode/forecast/operator_config.py
  ads/opctl/operator/lowcode/forecast/schema.yaml
  ads/opctl/operator/lowcode/forecast/utils.py
  tests/operators/forecast/test_errors.py
Labels: OCA Verified

#859 Refactor base handler
  ads/aqua/common/enums.py
  ads/aqua/extension/base_handler.py
  ads/aqua/extension/deployment_handler.py
  ads/aqua/extension/errors.py
  ads/aqua/extension/evaluation_handler.py
  ads/aqua/extension/finetune_handler.py
  ads/aqua/extension/model_handler.py
  ads/aqua/extension/ui_handler.py
  ads/aqua/extension/utils.py
  tests/unitary/with_extras/aqua/test_deployment_handler.py
  tests/unitary/with_extras/aqua/test_evaluation_handler.py
Labels: OCA Verified

#858 Copy verified configs for imported models
  ads/aqua/common/utils.py
  ads/aqua/constants.py
  ads/aqua/evaluation/evaluation.py
  ads/aqua/model/model.py
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified

#861 skip prompt when file is already uploaded to os
  ads/aqua/common/utils.py
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified

#864 AQUA. Enhance error message generated by HF.
  ads/aqua/extension/model_handler.py
  tests/unitary/with_extras/aqua/test_model_handler.py
Labels: OCA Verified

#863 Set default FT configs for unverified models and update validation API
  ads/aqua/config/config.py
  ads/aqua/finetuning/finetuning.py
  tests/unitary/with_extras/aqua/test_finetuning.py
Labels: OCA Verified

#862 Accept container family as input for model creation and param validation
  ads/aqua/common/enums.py
  ads/aqua/extension/deployment_handler.py
  ads/aqua/model/model.py
  ads/aqua/modeldeployment/constants.py
  ads/aqua/modeldeployment/deployment.py
  ads/aqua/modeldeployment/enums.py
  tests/unitary/with_extras/aqua/test_deployment.py
  tests/unitary/with_extras/aqua/test_deployment_handler.py
Labels: OCA Verified

#866 AQUA. Adds HF Login handler.
  ads/aqua/extension/common_handler.py
  ads/aqua/extension/model_handler.py
Labels: OCA Verified

#870 Add python 3.11
  .github/workflows/run-forecast-unit-tests.yml
Labels: OCA Verified

#868 Enable python 3.9, 3.10 tests for Operators
  .github/workflows/run-forecast-unit-tests.yml
  .github/workflows/run-operators-unit-tests.yml
  ads/opctl/operator/lowcode/anomaly/__main__.py
  ads/opctl/operator/lowcode/anomaly/model/autots.py
  ads/opctl/operator/lowcode/anomaly/schema.yaml
  ads/opctl/operator/lowcode/anomaly/utils.py
  ads/opctl/operator/lowcode/forecast/model/arima.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/autots.py
  ads/opctl/operator/lowcode/forecast/model/ml_forecast.py
  ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
  ads/opctl/operator/lowcode/forecast/model/prophet.py
  docs/source/user_guide/operators/anomaly_detection_operator/yaml_schema.rst
  test-requirements-operators.txt
  tests/operators/anomaly/test_anomaly_simple.py
Labels: OCA Verified

#860 Bug: mlforecast not taking datetime column from the spec
  ads/opctl/operator/lowcode/forecast/model/ml_forecast.py
Labels: OCA Verified

#872 Add config validation and telemetry
  ads/aqua/constants.py
  ads/aqua/model/model.py
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified
