Repository oracle/accelerated-data-science, pull requests merged in 2024-04, with the labels that each got.

#751 Temp regex fix
  ads/aqua/utils.py
  docs/source/release_notes.rst
  pyproject.toml
Labels: OCA Verified

#762 Python Validation error and doc fix
  ads/model/model_artifact_boilerplate/artifact_introspection_test/model_artifact_validate.py
  docs/source/user_guide/model_serialization/automlmodel.rst
  tests/unitary/default_setup/model/test_model_introspect.py
Labels: OCA Verified

#768 Create CODEOWNERS
  CODEOWNERS
Labels: OCA Verified

#758 ODSC-55407
  .github/workflows/run-operators-unit-tests.yml
  ads/common/serializer.py
  ads/opctl/operator/lowcode/forecast/environment.yaml
  test-requirements-operators.txt
Labels: OCA Verified

#765 Add AI quick actions link
  docs/source/index.rst
Labels: OCA Verified

#772 Forecast preprocessing schema
  ads/opctl/operator/lowcode/anomaly/model/anomaly_dataset.py
  ads/opctl/operator/lowcode/anomaly/operator_config.py
  ads/opctl/operator/lowcode/anomaly/schema.yaml
  ads/opctl/operator/lowcode/common/transformations.py
  ads/opctl/operator/lowcode/forecast/operator_config.py
  ads/opctl/operator/lowcode/forecast/schema.yaml
  tests/operators/forecast/test_errors.py
Labels: OCA Verified

#731 Bugfixes for output generation in case of series failure
  ads/dataset/label_encoder.py
  ads/opctl/operator/lowcode/forecast/model/arima.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/autots.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
  ads/opctl/operator/lowcode/forecast/model/prophet.py
  ads/opctl/operator/lowcode/forecast/utils.py
  tests/operators/data/rs_1_add.csv
  tests/operators/data/rs_1_prim.csv
  tests/operators/data/rs_2_add_encoded.csv
  tests/operators/data/rs_2_prim.csv
  tests/operators/forecast/test_errors.py
Labels: OCA Verified

#708 adding all original columns in anomaly outputs
  ads/opctl/operator/lowcode/anomaly/model/anomaly_dataset.py
  ads/opctl/operator/lowcode/anomaly/model/base_model.py
  ads/opctl/operator/lowcode/common/data.py
  ads/opctl/operator/lowcode/common/transformations.py
Labels: OCA Verified

#773 Add test cases for handlers: Evaluation/Common/Base
  tests/unitary/with_extras/aqua/test_evaluation_handler.py
  tests/unitary/with_extras/aqua/test_handlers.py
  tests/unitary/with_extras/aqua/utils.py
Labels: OCA Verified

#759 Update cli import
  ads/cli.py
  docs/source/release_notes.rst
  pyproject.toml
Labels: OCA Verified

#774 Added unit tests for model and ft handlers
  tests/unitary/with_extras/aqua/test_finetuning_handler.py
  tests/unitary/with_extras/aqua/test_model_handler.py
Labels: OCA Verified

#763 Unittests for aqua.evaluation/finetuning and handlers(evaluation/common/base)
  tests/unitary/with_extras/aqua/test_evaluation.py
  tests/unitary/with_extras/aqua/test_evaluation_handler.py
  tests/unitary/with_extras/aqua/test_finetuning.py
  tests/unitary/with_extras/aqua/test_handlers.py
  tests/unitary/with_extras/aqua/utils.py
Labels: OCA Verified

#776 Updated forecast operator unit tests
  tests/operators/forecast/test_errors.py
Labels: OCA Verified

#771 Added unit tests for get and create model
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified

#769 Update README.md
  README.md
Labels: OCA Verified

#777 ADSDataset.show_in_notebook fails while rendering visualizations
  ads/catalog/model.py
  ads/catalog/notebook.py
  ads/catalog/project.py
  ads/catalog/summary.py
  ads/data_labeling/metadata.py
  ads/dataset/dataset.py
  ads/dataset/factory.py
  ads/dataset/sampled_dataset.py
Labels: OCA Verified

#782 Bugfix/aqua error handle
  ads/aqua/decorator.py
  ads/aqua/extension/base_handler.py
  ads/aqua/extension/common_handler.py
  ads/aqua/extension/deployment_handler.py
  ads/aqua/extension/evaluation_handler.py
  ads/aqua/extension/finetune_handler.py
  ads/aqua/extension/ui_handler.py
  ads/aqua/extension/utils.py
  tests/unitary/with_extras/aqua/test_decorator.py
  tests/unitary/with_extras/aqua/test_evaluation_handler.py
  tests/unitary/with_extras/aqua/test_handlers.py
Labels: OCA Verified, ready for review, AQUA

#784 Adds supporting BLEU score metric for evaluation.
  ads/aqua/evaluation.py
  ads/config.py
Labels: OCA Verified

#770 Aqua deployment and UI tests
  tests/unitary/with_extras/aqua/test_data/deployment/aqua_create_deployment.yaml
  tests/unitary/with_extras/aqua/test_data/deployment/aqua_deployment_response.json
  tests/unitary/with_extras/aqua/test_data/deployment/aqua_finetuned_model.yaml
  tests/unitary/with_extras/aqua/test_data/deployment/aqua_foundation_model.yaml
  tests/unitary/with_extras/aqua/test_data/deployment/deployment_config.json
  tests/unitary/with_extras/aqua/test_data/ui/buckets_list.json
  tests/unitary/with_extras/aqua/test_data/ui/compartments_list.json
  tests/unitary/with_extras/aqua/test_data/ui/experiments_list.json
  tests/unitary/with_extras/aqua/test_data/ui/job_shapes_list.json
  tests/unitary/with_extras/aqua/test_data/ui/log_groups_list.json
  tests/unitary/with_extras/aqua/test_data/ui/logs_list.json
  tests/unitary/with_extras/aqua/test_data/ui/modelversionsets_list.json
  tests/unitary/with_extras/aqua/test_data/ui/resource_availability.json
  tests/unitary/with_extras/aqua/test_data/ui/root_compartment.json
  tests/unitary/with_extras/aqua/test_data/ui/subnets_list.json
  tests/unitary/with_extras/aqua/test_data/ui/vcn_list.json
  tests/unitary/with_extras/aqua/test_deployment.py
  tests/unitary/with_extras/aqua/test_deployment_handler.py
  tests/unitary/with_extras/aqua/test_ui.py
  tests/unitary/with_extras/aqua/test_ui_handler.py
Labels: OCA Verified

#780 Run unit tests only for source code (no docs and files from root)
  .github/workflows/run-unittests-default_setup.yml
  .github/workflows/run-unittests-py38-cov-report.yml
  .github/workflows/run-unittests-py39-py310.yml
Labels: OCA Verified

#789 Added support to force overwrite extsing file in object storage.
  ads/aqua/evaluation.py
  ads/aqua/finetune.py
Labels: OCA Verified

#790 Update release_notes.rst
  docs/source/release_notes.rst
Labels: OCA Verified

#785 [ODSC-56061] Update Model deployment telemetry
  ads/aqua/deployment.py
Labels: OCA Verified

#783 Added default compartment id for evaluation list.
  ads/aqua/evaluation.py
Labels: OCA Verified

#792 Update error message for create method failure
  ads/aqua/extension/base_handler.py
  tests/unitary/with_extras/aqua/test_handlers.py
Labels: OCA Verified

#791 Add test cases for checking content decoding
  tests/unitary/with_extras/aqua/test_data/valid_eval_artifact/report.html
  tests/unitary/with_extras/aqua/test_evaluation.py
Labels: OCA Verified, ready for review

#787 Added validation for fine tuning models.
  ads/aqua/finetune.py
  tests/unitary/with_extras/aqua/test_finetuning.py
Labels: OCA Verified

#796 Updated error message.
  ads/aqua/__init__.py
Labels: OCA Verified

#781 Updated source name for telemetry
  ads/aqua/evaluation.py
  ads/aqua/finetune.py
  tests/unitary/with_extras/aqua/test_evaluation.py
Labels: OCA Verified

#793 [ODSC-55947] Pretty print python fire output
  ads/cli.py
  ads/common/serializer.py
Labels: OCA Verified

#800 Followup comment in #795: reuse the logger in ads.init
  ads/aqua/__init__.py
  ads/aqua/evaluation.py
Labels: OCA Verified

#801 Removed redundant test
  tests/unitary/with_extras/aqua/test_global.py
Labels: OCA Verified

#786 Move to Report Creator
  THIRD_PARTY_LICENSES.txt
  ads/llm/serializers/runnable_parallel.py
  ads/opctl/operator/lowcode/anomaly/README.md
  ads/opctl/operator/lowcode/anomaly/environment.yaml
  ads/opctl/operator/lowcode/anomaly/model/automlx.py
  ads/opctl/operator/lowcode/anomaly/model/autots.py
  ads/opctl/operator/lowcode/anomaly/model/base_model.py
  ads/opctl/operator/lowcode/anomaly/model/tods.py
  ads/opctl/operator/lowcode/anomaly/schema.yaml
  ads/opctl/operator/lowcode/forecast/README.md
  ads/opctl/operator/lowcode/forecast/environment.yaml
  ads/opctl/operator/lowcode/forecast/model/arima.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/autots.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
  ads/opctl/operator/lowcode/forecast/model/prophet.py
  ads/opctl/operator/lowcode/forecast/schema.yaml
  ads/opctl/operator/lowcode/forecast/utils.py
  ads/opctl/operator/lowcode/pii/README.md
  ads/opctl/operator/lowcode/pii/environment.yaml
  ads/opctl/operator/lowcode/pii/model/report.py
  pyproject.toml
  tests/operators/anomaly/test_anomaly_simple.py
  tests/operators/forecast/test_datasets.py
  tests/operators/forecast/test_errors.py
  tests/unitary/with_extras/aqua/test_deployment_handler.py
  tests/unitary/with_extras/langchain/test_deploy.py
  tests/unitary/with_extras/langchain/test_guardrails.py
  tests/unitary/with_extras/langchain/test_serialization.py
  tests/unitary/with_extras/operator/forecast/test_model_automlx.py
  tests/unitary/with_extras/operator/forecast/test_model_autots.py
  tests/unitary/with_extras/operator/forecast/test_model_base_model.py
  tests/unitary/with_extras/operator/pii/test_guardrail.py
Labels: OCA Verified

#779 Fix telemetry event record to better report output
  ads/aqua/deployment.py
  ads/aqua/evaluation.py
  ads/aqua/finetune.py
Labels: OCA Verified

#804 Ability to disable packing of dataset in CLI
  ads/aqua/finetune.py
Labels: OCA Verified

#805 Upgraded oci version to support md custom egress.
  pyproject.toml
Labels: OCA Verified

#806 Add substring util
  ads/aqua/deployment.py
  ads/aqua/utils.py
Labels: OCA Verified

#803 Aqua v1.0.1 release
  ads/aqua/__init__.py
  ads/aqua/base.py
  ads/aqua/cli.py
  ads/aqua/decorator.py
  ads/aqua/deployment.py
  ads/aqua/evaluation.py
  ads/aqua/extension/base_handler.py
  ads/aqua/extension/common_handler.py
  ads/aqua/extension/deployment_handler.py
  ads/aqua/extension/evaluation_handler.py
  ads/aqua/extension/finetune_handler.py
  ads/aqua/extension/ui_handler.py
  ads/aqua/extension/utils.py
  ads/aqua/finetune.py
  ads/aqua/model.py
  ads/aqua/utils.py
  ads/cli.py
  ads/common/serializer.py
  ads/common/utils.py
  ads/config.py
  tests/unitary/with_extras/aqua/test_cli.py
  tests/unitary/with_extras/aqua/test_common_handler.py
  tests/unitary/with_extras/aqua/test_data/valid_eval_artifact/report.html
  tests/unitary/with_extras/aqua/test_decorator.py
  tests/unitary/with_extras/aqua/test_evaluation.py
  tests/unitary/with_extras/aqua/test_evaluation_handler.py
  tests/unitary/with_extras/aqua/test_finetuning.py
  tests/unitary/with_extras/aqua/test_global.py
  tests/unitary/with_extras/aqua/test_handlers.py
Labels: OCA Verified

#808 V2.11.8
  docs/source/release_notes.rst
  pyproject.toml
Labels: OCA Verified

#740 added version_id field to datascience model class
  ads/model/datascience_model.py
Labels: OCA Verified
