Repository oracle/accelerated-data-science, pull requests merged in 2024-02, with the labels that each got.

#554 ODSC-52172: Adds unit tests for the playground backend.
  ads/aqua/extension/__init__.py
  ads/aqua/extension/base_handler.py
  ads/aqua/extension/comon_handler.py
  ads/aqua/extension/playground_handler.py
  ads/aqua/playground/const.py
  ads/aqua/playground/db_context.py
  ads/aqua/playground/db_models.py
  ads/aqua/playground/entities.py
  ads/aqua/playground/errors.py
  ads/aqua/playground/playground.py
  ads/common/decorator/require_nonempty_arg.py
  ads/common/utils.py
  tests/unitary/default_setup/common/test_require_nonempty_arg.py
  tests/unitary/with_extras/aqua/test_playground_entities.py
Labels: OCA Verified

#560 Deployment params for UI
  ads/aqua/base.py
  ads/aqua/deployment.py
Labels: OCA Verified

#558 Operator in Jobs should auto-detect RP
  ads/common/auth.py
  ads/opctl/config/merger.py
Labels: OCA Verified

#559 Revisit error handler
  ads/aqua/deployment.py
  ads/aqua/model.py
Labels: OCA Verified

#562 odsc-52392/list model api improvement
  ads/aqua/base.py
  ads/aqua/extension/model_handler.py
  ads/aqua/model.py
  ads/aqua/utils.py
  ads/config.py
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified, AQUA

#565 Aqua/improve list model api
  ads/aqua/extension/model_handler.py
  ads/aqua/model.py
Labels: OCA Verified

#566 fixed bug
  ads/aqua/extension/model_handler.py
Labels: OCA Verified

#561 [ODSC_52446_52447] Get loggroups logids and compartment list
  ads/aqua/base.py
  ads/aqua/deployment.py
  ads/aqua/extension/__init__.py
  ads/aqua/extension/deployment_handler.py
  ads/aqua/extension/ui_handler.py
  ads/aqua/model.py
  ads/aqua/ui.py
  ads/common/oci_client.py
  ads/common/utils.py
Labels: OCA Verified

#564 Create Aqua Model
  ads/aqua/deployment.py
  ads/aqua/extension/deployment_handler.py
  ads/aqua/model.py
  ads/config.py
Labels: OCA Verified

#568 [ODSC-51508] : Refactor results dir unique path creation
  ads/opctl/operator/lowcode/anomaly/model/base_model.py
  ads/opctl/operator/lowcode/common/utils.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
Labels: OCA Verified

#563 Ad/add support for valid data
  ads/opctl/operator/common/operator_config.py
  ads/opctl/operator/lowcode/anomaly/__main__.py
  ads/opctl/operator/lowcode/anomaly/environment.yaml
  ads/opctl/operator/lowcode/anomaly/model/anomaly_dataset.py
  ads/opctl/operator/lowcode/anomaly/model/automlx.py
  ads/opctl/operator/lowcode/anomaly/model/autots.py
  ads/opctl/operator/lowcode/anomaly/model/base_model.py
  ads/opctl/operator/lowcode/anomaly/model/factory.py
  ads/opctl/operator/lowcode/anomaly/model/tods.py
  ads/opctl/operator/lowcode/anomaly/operator_config.py
  ads/opctl/operator/lowcode/anomaly/schema.yaml
  ads/opctl/operator/lowcode/anomaly/utils.py
  ads/opctl/operator/lowcode/common/data.py
  ads/opctl/operator/lowcode/common/utils.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/base_model.py
  ads/opctl/operator/lowcode/forecast/operator_config.py
  ads/opctl/operator/lowcode/forecast/schema.yaml
  pyproject.toml
  tests/operators/anomaly/test_anomaly_simple.py
Labels: OCA Verified

#553 ODSC-51511 : Fallback method to train model for the AD models
  ads/opctl/operator/lowcode/anomaly/model/base_model.py
Labels: OCA Verified

#567 Aqua/list model api v3
  ads/aqua/model.py
Labels: OCA Verified, wip, AQUA

#572 Fixed ads model deployment issue.
  ads/model/deployment/model_deployment.py
Labels: OCA Verified

#571 Odsc-52627/get default compartment
  ads/aqua/extension/ui_handler.py
  ads/aqua/ui.py
Labels: OCA Verified

#573 bugfix/fix_get_default_compartment_return_type
  ads/aqua/ui.py
Labels: OCA Verified

#574 Integration testing changes
  ads/aqua/deployment.py
  ads/aqua/extension/deployment_handler.py
  ads/aqua/extension/ui_handler.py
  ads/config.py
Labels: OCA Verified

#570 Added get shape config api
  ads/aqua/deployment.py
  ads/aqua/extension/deployment_handler.py
  ads/aqua/model.py
  ads/aqua/utils.py
Labels: OCA Verified

#577 adding more tests
  ads/opctl/operator/lowcode/anomaly/model/anomaly_dataset.py
  ads/opctl/operator/lowcode/anomaly/model/base_model.py
  ads/opctl/operator/lowcode/common/data.py
  ads/opctl/operator/lowcode/common/utils.py
  ads/opctl/operator/lowcode/forecast/model/arima.py
  ads/opctl/operator/lowcode/forecast/model/automlx.py
  ads/opctl/operator/lowcode/forecast/model/forecast_datasets.py
  ads/opctl/operator/lowcode/forecast/model/neuralprophet.py
  tests/operators/forecast/test_datasets.py
  tests/operators/forecast/test_errors.py
Labels: OCA Verified

#579 Aqua/fix/tag validation in list
  ads/aqua/model.py
Labels: OCA Verified

#581 Added lifecycle details to get model deployment.
  ads/aqua/deployment.py
Labels: OCA Verified

#580 ADS release v2.10.1
  docs/source/release_notes.rst
  pyproject.toml
Labels: OCA Verified

#582 fix concatenation
  ads/aqua/extension/__init__.py
Labels: OCA Verified

#585 aqua/add fire as aqua dependency
  pyproject.toml
Labels: OCA Verified

#583 Remove version from docs
  README.md
  ads/opctl/operator/lowcode/anomaly/__main__.py
  pyproject.toml
Labels: OCA Verified

#548 Aqua Exception Design
  ads/aqua/base.py
  ads/aqua/decorator.py
  ads/aqua/deployment.py
  ads/aqua/exception.py
  ads/aqua/extension/base_handler.py
  ads/aqua/extension/model_handler.py
  ads/aqua/model.py
  ads/aqua/ui.py
  ads/aqua/utils.py
Labels: OCA Verified, needs attention, AQUA

#591 load_icon moved to AquaModelSummary
  ads/aqua/model.py
Labels: OCA Verified

#590 Support Distributed Training with Container Jobs.
  ads/jobs/builders/infrastructure/dsc_job.py
  ads/jobs/builders/runtimes/base.py
  ads/jobs/builders/runtimes/container_runtime.py
  ads/jobs/builders/runtimes/pytorch_runtime.py
Labels: OCA Verified

#593 Updated aqua model creation api to support model by reference.
  ads/aqua/model.py
Labels: OCA Verified

#588 AQUA inference handler
  ads/aqua/deployment.py
  ads/aqua/extension/deployment_handler.py
Labels: OCA Verified

#595 Aqua/list model v4
  ads/aqua/model.py
  test-requirements.txt
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified, AQUA

#594 Updated to Only Copy Service Model
  ads/aqua/deployment.py
  ads/aqua/model.py
Labels: OCA Verified

#586 [ODSC-50335] Model by Reference Implementation
  ads/aqua/deployment.py
  ads/aqua/model.py
  ads/common/object_storage_details.py
  ads/common/utils.py
  ads/model/artifact_downloader.py
  ads/model/artifact_uploader.py
  ads/model/datascience_model.py
  ads/model/generic_model.py
  ads/model/model_file_description_schema.json
  ads/model/model_metadata.py
  ads/model/service/oci_datascience_model.py
  tests/unitary/default_setup/model/test_artifact_downloader.py
  tests/unitary/default_setup/model/test_artifact_uploader.py
  tests/unitary/default_setup/model/test_datascience_model.py
  tests/unitary/default_setup/model/test_files/model_description.json
  tests/unitary/default_setup/model/test_oci_datascience_model.py
  tests/unitary/with_extras/model/test_generic_model.py
Labels: OCA Verified

#598 Create RP when in OCI resources
  ads/aqua/base.py
Labels: OCA Verified

#596 build base class and construct sample response
  ads/aqua/evaluation.py
  ads/aqua/extension/__init__.py
  ads/aqua/extension/evaluation_handler.py
  ads/aqua/extension/ui_handler.py
  ads/aqua/ui.py
Labels: OCA Verified, AQUA

#597 Env vars added to aqua deployment
  ads/aqua/base.py
  ads/aqua/deployment.py
  ads/aqua/utils.py
Labels: OCA Verified

#601 AQUA/EVAL/Add 4 new handlers based on requirements
  ads/aqua/base.py
  ads/aqua/evaluation.py
  ads/aqua/extension/deployment_handler.py
  ads/aqua/extension/evaluation_handler.py
  ads/aqua/extension/model_handler.py
  ads/aqua/extension/ui_handler.py
  ads/aqua/ui.py
Labels: OCA Verified, AQUA

#603 Aqua/eval/mock response create panel
  ads/aqua/evaluation.py
Labels: OCA Verified

#600 [WIP] Added api to create evaluation.
  ads/aqua/deployment.py
  ads/aqua/evaluation.py
  ads/aqua/extension/evaluation_handler.py
  ads/aqua/extension/utils.py
  ads/aqua/model.py
  ads/aqua/utils.py
  ads/config.py
Labels: OCA Verified

#605 fix/aqua/eval/add key field in metrics dataclass
  ads/aqua/evaluation.py
Labels: OCA Verified

#606 Make project_id optional.
  ads/aqua/evaluation.py
Labels: OCA Verified

#599 Aqua/eval/implementation for List and Get
  ads/aqua/evaluation.py
  ads/aqua/exception.py
  ads/aqua/extension/evaluation_handler.py
  ads/aqua/utils.py
  ads/model/datascience_model.py
  tests/unitary/with_extras/aqua/test_evaluation.py
  tests/unitary/with_extras/aqua/test_utils.py
Labels: OCA Verified

#592 [ODSC-52993] Set up caching for listing models and compartments
  THIRD_PARTY_LICENSES.txt
  ads/aqua/extension/model_handler.py
  ads/aqua/extension/ui_handler.py
  ads/aqua/model.py
  ads/aqua/ui.py
  pyproject.toml
Labels: OCA Verified

#608 Aqua/fix/status code inconsistency
  ads/aqua/extension/base_handler.py
  ads/aqua/extension/model_handler.py
Labels: OCA Verified

#602 AQUA/EVAL/ODSC-53263/download report
  ads/aqua/evaluation.py
  ads/aqua/exception.py
  ads/aqua/utils.py
  tests/unitary/with_extras/aqua/test_data/__init__.py
  tests/unitary/with_extras/aqua/test_data/valid_eval_artifact/metric1.md
  tests/unitary/with_extras/aqua/test_data/valid_eval_artifact/report.html
  tests/unitary/with_extras/aqua/test_evaluation.py
Labels: OCA Verified, ready for review, AQUA

#607 Odsc 53443/eval/get eval metrics md
  ads/aqua/evaluation.py
  ads/aqua/utils.py
  tests/unitary/with_extras/aqua/test_data/valid_eval_artifact/report.json
  tests/unitary/with_extras/aqua/test_evaluation.py
Labels: OCA Verified

#611 aqua/fix failed test
  tests/unitary/with_extras/aqua/test_utils.py
Labels: OCA Verified

#610 Odsc-53635/eval/get status api
  ads/aqua/evaluation.py
  ads/aqua/utils.py
  tests/unitary/with_extras/aqua/test_evaluation.py
Labels: OCA Verified, AQUA

#604 Support using custom authentication for data science jobs
  ads/common/oci_logging.py
  ads/common/oci_mixin.py
  ads/jobs/ads_job.py
  ads/jobs/builders/infrastructure/base.py
  ads/jobs/builders/infrastructure/dsc_job.py
  ads/jobs/builders/runtimes/base.py
  tests/unitary/with_extras/langchain/test_serialization.py
  tests/unitary/with_extras/operator/pii/test_guardrail.py
Labels: OCA Verified

#613 aqua/fix/download report in nested structure
  ads/aqua/evaluation.py
Labels: OCA Verified

#615 Support eval CLI
  ads/aqua/cli.py
Labels: OCA Verified

#614 Fix/temp soln for load metrics
  ads/aqua/evaluation.py
  tests/unitary/with_extras/aqua/test_data/valid_eval_artifact/report.json
Labels: OCA Verified

#616 Patching for create
  ads/aqua/evaluation.py
  ads/aqua/utils.py
Labels: OCA Verified

#617 fixed get default config
  ads/aqua/evaluation.py
Labels: OCA Verified

#619 aqua/fix/evaluation status
  ads/aqua/evaluation.py
  ads/aqua/utils.py
Labels: OCA Verified

#624 Quick fix
  ads/aqua/evaluation.py
Labels: OCA Verified
