Repository oracle/accelerated-data-science, pull requests merged in 2025-04, with the labels that each got.

#1139 Add docker code
  docs/source/user_guide/aqua/apiserver.rst
Labels: OCA Verified

#1142 fix typo in the doc
  docs/source/user_guide/aqua/apiserver.rst
Labels: OCA Verified

#1140 [Ready To Merge] Adds supporting of the OpenAI and AsyncOpenAI Clients
  ads/aqua/client/openai_client.py
  docs/source/user_guide/large_language_model/aqua_client.rst
Labels: OCA Verified

#1144 [Multi model deployment] Updating usages for container config
  ads/aqua/config/container_config.py
  ads/aqua/model/model.py
  ads/aqua/modeldeployment/deployment.py
  tests/unitary/with_extras/aqua/test_data/ui/container_index.json
  tests/unitary/with_extras/aqua/test_ui.py
Labels: OCA Verified

#1141 Corrected: Improved AQUA Error Messages for Authorization and Tag-Related Uses
  ads/aqua/constants.py
  ads/aqua/extension/aqua_ws_msg_handler.py
  ads/aqua/extension/base_handler.py
  ads/aqua/extension/errors.py
  ads/aqua/extension/utils.py
  tests/unitary/with_extras/aqua/test_decorator.py
  tests/unitary/with_extras/aqua/test_handlers.py
  tests/unitary/with_extras/aqua/test_model_handler.py
Labels: OCA Verified

#1145 Bumps ADS version to 2.13.5
  docs/source/release_notes.rst
  pyproject.toml
Labels: OCA Verified

#1106 correct ARM architecture detection regex in Docker image build for opctl
  ads/opctl/utils.py
Labels: OCA Verified

#1146 misc: fix spelling in json,md,rst files
  README-development.md
  docs/source/user_guide/configuration/configuration.rst
  docs/source/user_guide/configuration/vault.rst
  docs/source/user_guide/data_flow/dataflow.rst
  docs/source/user_guide/data_flow/legacy_dataflow.rst
  docs/source/user_guide/operators/anomaly_detection_operator/use_cases.rst
  docs/source/user_guide/quick_start/quick_start.rst
  tests/unitary/with_extras/model/index.json
Labels: OCA Verified

#1148 Enhance the container family validation for multi-model deployment
  ads/aqua/common/enums.py
  ads/aqua/common/utils.py
  ads/aqua/model/model.py
  tests/unitary/with_extras/aqua/test_common_utils.py
Labels: OCA Verified

#1149 [Bug fix] Report generator script for PII operator
  ads/dataset/recommendation.py
  ads/opctl/operator/lowcode/pii/model/report.py
Labels: OCA Verified

#1150 ADS Release v2.13.6
  docs/source/release_notes.rst
  pyproject.toml
Labels: OCA Verified

#1058 [DRCC][Ready to Merge] AQUA MS Enhancements
  ads/aqua/app.py
  ads/aqua/common/utils.py
  ads/aqua/config/config.py
  ads/aqua/config/container_config.py
  ads/aqua/config/evaluation/evaluation_service_config.py
  ads/aqua/constants.py
  ads/aqua/evaluation/evaluation.py
  ads/aqua/extension/common_handler.py
  ads/aqua/extension/model_handler.py
  ads/aqua/extension/models/ws_models.py
  ads/aqua/extension/models_ws_msg_handler.py
  ads/aqua/finetuning/entities.py
  ads/aqua/finetuning/finetuning.py
  ads/aqua/model/constants.py
  ads/aqua/model/entities.py
  ads/aqua/model/model.py
  ads/aqua/modeldeployment/deployment.py
  ads/aqua/modeldeployment/utils.py
  ads/aqua/ui.py
  ads/model/datascience_model.py
  ads/model/service/oci_datascience_model.py
  tests/unitary/with_extras/aqua/test_common_handler.py
  tests/unitary/with_extras/aqua/test_config.py
  tests/unitary/with_extras/aqua/test_data/finetuning/ft_config.json
  tests/unitary/with_extras/aqua/test_deployment.py
  tests/unitary/with_extras/aqua/test_evaluation.py
  tests/unitary/with_extras/aqua/test_finetuning.py
  tests/unitary/with_extras/aqua/test_model.py
  tests/unitary/with_extras/aqua/test_model_handler.py
  tests/unitary/with_extras/aqua/test_ui.py
  tests/unitary/with_extras/aqua/utils.py
Labels: enhancement, OCA Verified, AQUA

#1147 [DRCC][AQUA] Completely Removing OSS bucket config dependency
  ads/aqua/__init__.py
  ads/aqua/cli.py
  ads/aqua/common/utils.py
  ads/aqua/config/container_config.py
  ads/aqua/extension/common_ws_msg_handler.py
  ads/aqua/extension/model_handler.py
  ads/aqua/extension/utils.py
  ads/aqua/model/model.py
  ads/aqua/modeldeployment/deployment.py
  ads/config.py
  tests/unitary/with_extras/aqua/test_cli.py
  tests/unitary/with_extras/aqua/test_common_handler.py
  tests/unitary/with_extras/aqua/test_model.py
  tests/unitary/with_extras/aqua/test_model_handler.py
  tests/unitary/with_extras/aqua/test_ui.py
Labels: OCA Verified, AQUA

#1151 Updated train metrics generation for AutoMLX model
  ads/opctl/operator/lowcode/forecast/model/automlx.py
Labels: OCA Verified

#1135 AD fixes: preprocessing steps, raise e remove
  ads/opctl/operator/lowcode/anomaly/model/anomaly_dataset.py
  ads/opctl/operator/lowcode/anomaly/model/base_model.py
  ads/opctl/operator/lowcode/anomaly/operator_config.py
  ads/opctl/operator/lowcode/common/transformations.py
Labels: OCA Verified

#1153 update docs
  docs/source/user_guide/operators/forecast_operator/images/forecast_conda.png
  docs/source/user_guide/operators/forecast_operator/images/notebook_form.png
  docs/source/user_guide/operators/forecast_operator/images/notebook_form_filled.png
  docs/source/user_guide/operators/forecast_operator/index.rst
  docs/source/user_guide/operators/forecast_operator/install.rst
  docs/source/user_guide/operators/forecast_operator/yaml_schema.rst
Labels: OCA Verified

#1152 Fixed ads dataset key error
  ads/type_discovery/typed_feature.py
Labels: OCA Verified

#1155 Update AutoGen docs
  docs/source/user_guide/large_language_model/autogen_integration.rst
Labels: OCA Verified

#1156 Bumps ADS version to 2.13.7
  docs/source/release_notes.rst
  pyproject.toml
Labels: OCA Verified

#1157 Relaxes the validation of model task types during multi-model deployment creation.
  ads/aqua/model/model.py
Labels: OCA Verified

#1158 Bumps ADS version to 2.13.8
  docs/source/release_notes.rst
  pyproject.toml
Labels: OCA Verified

#1164 Adding defined metadata to fine-tuned model
  ads/aqua/finetuning/finetuning.py
  ads/aqua/model/model.py
Labels: OCA Verified

#1169 Adopt model file descriptions while creating multi model
  ads/aqua/constants.py
  ads/aqua/model/entities.py
  ads/aqua/model/model.py
  tests/unitary/with_extras/aqua/test_model.py
Labels: OCA Verified
